import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const mainSource = readFileSync(join(root, "src", "main", "main.ts"), "utf8");
const preloadSource = readFileSync(join(root, "src", "preload", "preload.ts"), "utf8");
const storeSource = readFileSync(join(root, "src", "renderer", "panels-chat-bottom-store.ts"), "utf8");
const ipcContractSource = readFileSync(join(root, "src", "shared", "ipc-contract.ts"), "utf8");
const animationSource = readFileSync(join(root, "src", "renderer", "PanelsChatBottomSlice.tsx"), "utf8");
const brainCanvasSource = readFileSync(join(root, "src", "renderer", "BrainCanvas.tsx"), "utf8");
const stylesSource = readFileSync(join(root, "src", "renderer", "styles.css"), "utf8");
const agentActionLoopSource = readFileSync(join(root, "src", "main", "agent-action-loop.ts"), "utf8");
const brainMemorySource = readFileSync(join(root, "src", "renderer", "brain-user-memory-store.ts"), "utf8");
const normalizedMainSource = mainSource.replace(/\r\n/g, "\n");

describe("assistant progressive response feed", () => {
  it("pushes transcript snapshot events while a chat command is still running", () => {
    expect(ipcContractSource).toContain("export interface PanelsChatBottomSnapshotEvent");
    expect(ipcContractSource).toContain("export interface AgentRuntimeEvent");
    expect(ipcContractSource).toContain('schema: "ingen.agent_runtime.event.v1"');
    expect(preloadSource).toContain('ipcRenderer.on("forge:panels-chat-bottom-snapshot-event"');
    expect(preloadSource).toContain('ipcRenderer.on("forge:agent-runtime-event"');
    expect(storeSource).toContain("api?.onPanelsChatBottomSnapshotEvent?.");
    expect(mainSource).toContain('webContents.send("forge:panels-chat-bottom-snapshot-event"');
    expect(mainSource).toContain('webContents.send("forge:agent-runtime-event"');
  });

  it("seeds large assistant messages before committing the full final response", () => {
    expect(mainSource).toContain("ASSISTANT_PROGRESSIVE_SEED_MIN_CHARS");
    expect(mainSource).toContain("commitAssistantMessageWithProgressiveSeed");
    expect(mainSource).toContain('emitPanelsChatBottomSnapshotEvent("assistant_progressive_seed"');
    expect(storeSource).toContain("incomingHasFreshAssistantResponse");
  });

  it("keeps the assistant writing animation from leaking silent rename tags", () => {
    expect(animationSource).toContain("function assistantRenderableText");
    expect(animationSource).toContain("BRAIN_RENAME_SESSION_COMMAND");
    expect(animationSource).toContain("RENAME_SESSION_TAG_PATTERN");
    expect(animationSource).toContain("RENAME_SESSION_TAG_FRAGMENT_PATTERN");
    expect(animationSource).toContain("trimmed.startsWith(BRAIN_RENAME_SESSION_COMMAND)");
    expect(animationSource).toContain("line.replace(RENAME_SESSION_TAG_FRAGMENT_PATTERN");
    expect(animationSource).not.toContain("rename" + "chat");
    expect(animationSource).toContain("assistantRenderableText(text)");
    expect(animationSource).toContain("function AnimatedAssistantText");
    expect(animationSource).toContain("const renderableText = useMemo(() => assistantRenderableText(message.text), [message.text]);");
    expect(animationSource).toContain("const animationSource = useMemo(() => assistantVisibleAnimationSource(renderableText), [renderableText]);");
    expect(animationSource).toContain("const visibleText = animationSource.slice(0, visibleCharacters);");
  });

  it("keeps pending-response animation live across session materialization", () => {
    expect(animationSource).toContain("const keepDraftResponseLive = previous.hadPending");
    expect(animationSource).not.toContain('previous.sessionId === "" && previous.hadPending');
  });

  it("does not lock the transcript scroll while assistant text is streaming", () => {
    expect(animationSource).toContain("TRANSCRIPT_FOLLOW_BOTTOM_THRESHOLD_PX");
    expect(animationSource).toContain("function transcriptIsNearBottom");
    expect(animationSource).toContain("const followLatestTranscriptRef = useRef(true)");
    expect(animationSource).toContain('container.addEventListener("scroll", updateFollowMode, { passive: true })');
    expect(animationSource).toContain("followLatestTranscriptRef.current = transcriptIsNearBottom(container)");
    expect(animationSource).toContain("if (!followLatestTranscriptRef.current && !transcriptIsNearBottom(container))");
    expect(animationSource).toContain('followTranscriptLatest(container, latestMessage?.role === "user" ? "smooth" : "instant")');
    expect(animationSource).not.toContain("followTranscriptLatest(messagesRef.current, \"smooth\")");
  });

  it("smooths assistant line growth while the writing animation wraps", () => {
    expect(animationSource).toContain("ASSISTANT_LINE_GROWTH_MIN_DELTA_PX");
    expect(animationSource).toContain("ASSISTANT_LINE_GROWTH_TRANSITION_MS");
    expect(animationSource).toContain("const lineGrowthStartHeightRef = useRef<number | null>(null)");
    expect(animationSource).toContain("lineGrowthStartHeightRef.current = textRef.current?.getBoundingClientRect().height ?? null");
    expect(animationSource).toContain("const targetHeight = node.scrollHeight");
    expect(animationSource).toContain("node.style.transition = `height ${ASSISTANT_LINE_GROWTH_TRANSITION_MS}ms cubic-bezier(0.22, 1, 0.36, 1)`");
    expect(animationSource).toContain("node.style.overflow = \"hidden\"");
    expect(animationSource).toContain("node.style.removeProperty(\"height\")");
    expect(animationSource).toContain("prefersReducedMotion()");
  });

  it("reveals styled inline markdown only at parsed-safe breakpoints", () => {
    expect(animationSource).toContain("ASSISTANT_INLINE_ATOMIC_PATTERN");
    expect(animationSource).toContain("function assistantInlineAtomicRanges");
    expect(animationSource).toContain("function assistantBreakpointInsideAtomicRange");
    expect(animationSource).toContain("const atomicRanges = assistantInlineAtomicRanges(text)");
    expect(animationSource).toContain("!assistantBreakpointInsideAtomicRange(point, atomicRanges)");
    expect(animationSource).toContain("while ((match = ASSISTANT_INLINE_ATOMIC_PATTERN.exec(text)) !== null)");
    expect(animationSource).toContain("__[^_\\n]+?__");
    expect(animationSource).toContain("_[^_\\n]+?_");
    expect(animationSource).toContain('} else if (token.startsWith("__"))');
    expect(animationSource).toContain('} else if (token.startsWith("_"))');
  });

  it("runs agent action requests as a visible loop stream", () => {
    expect(agentActionLoopSource).toContain('export const AGENT_ACTION_JSON_PREFIX = "AGENT_ACTION_JSON"');
    expect(mainSource).toContain('const AGENT_ACTION_RESULT_PREFIX = "AGENT_ACTION_RESULT v1"');
    expect(mainSource).toContain("function executeAssistantAgentActionLoop");
    expect(mainSource).toContain("interface AgentRuntimeEventQueue");
    expect(mainSource).toContain("function createAgentRuntimeEventQueue");
    expect(mainSource).toContain("agentEvents: AgentRuntimeEventQueue");
    expect(mainSource).toContain("extractAgentActionJsonRequest(assistantMessage.text)");
    expect(mainSource).toContain("executeAgentActionRequest(agentActionHostConfig(), request)");
    expect(mainSource).toContain("function agentLoopNarrationContractManifest");
    expect(mainSource).toContain("LOOP_STREAM_NARRATION_CONTRACT v1");
    expect(mainSource).toContain("ACTION_NARRATION_CONTRACT v1");
    expect(mainSource).toContain("BRAIN_PERSONALITY_MANIFEST v1");
    expect(mainSource).toContain("voice=Sound like a present, capable desktop agent");
    expect(brainMemorySource).toContain("voice=Sound like a present, capable desktop agent");
    expect(brainMemorySource).toContain('parsed.trust !== "user_confirmed"');
    expect(brainCanvasSource).toContain("personalityManifestToMacroRows");
    expect(brainCanvasSource).toContain('line !== "BRAIN_PERSONALITY_MANIFEST v1"');
    expect(brainCanvasSource).toContain("personalityMacroRowsToManifest");
    expect(brainCanvasSource).not.toContain("value={personalityMemory.manifest}");
    expect(brainCanvasSource).toContain("Choose how the agent speaks while it works");
    expect(brainCanvasSource).not.toContain("How the agent sounds when it thinks");
    expect(brainCanvasSource).toContain("Agent voice");
    expect(brainCanvasSource).not.toContain("Loop-stream voice contract");
    expect(brainCanvasSource).not.toContain("Injected with the Brain manifest");
    expect(brainCanvasSource).toContain("BRAIN_PERSONALITY_PRESETS");
    expect(brainCanvasSource).toContain('label: "Elon Musk"');
    expect(brainCanvasSource).toContain("Do not impersonate Elon Musk");
    expect(brainCanvasSource).toContain("applyPersonalityPreset");
    expect(stylesSource).toContain(".brainPersonalityMacroRow");
    expect(stylesSource).toContain(".brainPersonalityPresetStack");
    expect(stylesSource).toContain(".brainPersonalityPreset::before");
    expect(stylesSource).toContain("overflow: hidden;");
    expect(mainSource).toContain("voice_source=Follow BRAIN_PERSONALITY_MANIFEST");
    expect(mainSource).toContain("function brainPersonalityContextManifest");
    expect(mainSource).toContain("personalityManifest");
    expect(mainSource).toContain("visible_step_shape=Each visible paragraph should make the step understandable");
    expect(mainSource).toContain("event_coupling=When you say an action will be taken");
    expect(mainSource).toContain("pedagogy=Name pivots and tradeoffs plainly");
    expect(mainSource).toContain("completion=When no further loop action is needed");
    expect(mainSource).toContain("emitAgentRuntimeToolCallStarted");
    expect(mainSource).toContain('kind: "tool_call_started"');
    expect(mainSource).toContain('kind: "tool_result"');
    expect(mainSource).toContain('kind: "tool_call_completed"');
    expect(mainSource).toContain("agentActionLoopContinuationUserText");
    expect(mainSource).toContain("agentActionStepNeedsMutationFollowUp");
    expect(mainSource).toContain("agentActionForcedContinuationUserText");
    expect(mainSource).toContain("AGENT_ACTION_FORCED_CONTINUATION v1");
    expect(mainSource).toContain("applyDeterministicOrganizationFallback");
    expect(mainSource).toContain("deterministicOrganizationRequestsFromList");
    expect(mainSource).toContain("function renderPendingAgentActionText");
    expect(mainSource).toContain("function renderCompletedPendingAgentActionText");
    expect(mainSource).toContain("agentActionLoopPendingStep");
    expect(mainSource).toContain("deterministicAgentActionFallbackPending");
    expect(mainSource).toContain("const fallbackMessage = await applyDeterministicOrganizationFallback");
    expect(mainSource).toContain("function emitAgentLoopDiagnosticSummary");
    expect(mainSource).toContain('outcome: "completed"');
    expect(mainSource).toContain('outcome: reportableAgentActionLoopOutcome(loopState, "blocked")');
    expect(mainSource).not.toContain('outcome: "max_steps"');
    expect(mainSource).toContain("tool_steps=");
    expect(mainSource).toContain("params.commitTranscript(transcriptWithMessage(params.baseTranscript, assistantMessage))");
    expect(mainSource).toContain("assistantMessage = await executeAssistantAgentActionLoop({");
    expect(agentActionLoopSource).toContain("let markerIndex = text.indexOf(AGENT_ACTION_JSON_PREFIX)");
    expect(agentActionLoopSource).toContain("export function jsonObjectEndIndex");
    expect(agentActionLoopSource).toContain("export function removeAgentActionJsonFragment");
    expect(agentActionLoopSource).toContain("export function agentActionLiveVisibleText");
  });

  it("streams provider text into the transcript and cuts over to tools live", () => {
    expect(mainSource).toContain("interface ProviderLiveTextSink");
    expect(mainSource).toContain("interface AssistantProviderAdapter");
    expect(mainSource).toContain("const ASSISTANT_PROVIDER_ADAPTERS");
    expect(mainSource).toContain("function assistantProviderAdapterFor");
    expect(mainSource).toContain("const adapter = assistantProviderAdapterFor(profile)");
    expect(mainSource).toContain("const run = await adapter.run");
    expect(mainSource).toContain("async function readCodexDirectEventStream(response: Response, liveSink?: ProviderLiveTextSink)");
    expect(mainSource).toContain("liveSink?.onText(finalText.trimEnd())");
    expect(mainSource).toContain("liveSink?.shouldStop?.(finalText)");
    expect(mainSource).toContain("await reader.cancel().catch(() => undefined)");
    expect(mainSource).toContain("function runProviderCommandStreamingText");
    expect(mainSource).toContain("claudeStreamLineText");
    expect(mainSource).toContain("async function readOpenRouterChatCompletionStream(response: Response, liveSink?: ProviderLiveTextSink)");
    expect(mainSource).toContain("function openRouterStreamDeltaText");
    expect(mainSource).toContain("body.stream = true");
    expect(mainSource).toContain("runOpenRouterChatCompletion(");
    expect(mainSource).toContain("params.profile");
    expect(mainSource).toContain("params.providerUserText");
    expect(mainSource).toContain("function createAssistantLiveTextSink");
    expect(mainSource).toContain("renameSession?: SidebarSessionItem");
    expect(mainSource).toContain("renameChatSession(params.renameSession, request)");
    expect(mainSource).toContain("removeRenameSessionCodeActLines(agentActionLiveVisibleText(text))");
    expect(mainSource).toContain("transcriptWithReplacedMessage(params.baseTranscript, liveMessage)");
    expect(mainSource).toContain("renameSession: session");
    expect(storeSource).toContain('event.reason === "assistant_progressive_seed"');
    expect(storeSource).toContain("void sidebarShadowStore.boot()");
    expect(mainSource).toContain("shouldStop: (text) => Boolean(params.assistantRun?.cancelled || extractAgentActionJsonRequest(text))");
    expect(mainSource).toContain("liveTextSink");
    expect(mainSource).toContain("continuationLiveSink");
    expect(mainSource).toContain('kind: "text_delta"');
  });

  it("lets the composer stop an active assistant run", () => {
    expect(animationSource).toContain("snapshot.composer.assistantBusy");
    expect(animationSource).toContain('activityText = "is thinking"');
    expect(animationSource).toContain("ASSISTANT_WORKING_STATUS_DELAY_MS");
    expect(animationSource).toContain("ASSISTANT_WORKING_STATUS_EXIT_MS");
    expect(animationSource).toContain("function AssistantWorkingStatus");
    expect(animationSource).toContain("function agentWorkingStatusText");
    expect(animationSource).toContain("function canShowAssistantWorkingStatus");
    expect(animationSource).toContain("assistantWorkingCandidate && canShowAssistantWorkingStatus(assistantWorkingEvent)");
    expect(animationSource).toContain("is continuing in ${brainSegmentName(event.command)}");
    expect(animationSource).toContain("return true;");
    expect(animationSource).toContain("sessionRow__loaderViewbox assistantThinkingEvent__loaderViewbox");
    expect(animationSource).toContain("latestTranscriptEvent(message.text)");
    expect(animationSource).toContain("is running a confirmed shell command");
    expect(animationSource).toContain("is inspecting files");
    expect(animationSource).toContain("is applying a local action");
    expect(stylesSource).toContain("assistantThinkingEvent__loaderViewbox");
    expect(stylesSource).toContain(".assistantText--pending .loader");
    expect(stylesSource).toContain("assistantWorkingEvent--leaving");
    expect(stylesSource).toContain("assistantWorkingStatusIn");
    expect(stylesSource).toContain("assistantWorkingStatusOut");
    expect(animationSource).not.toContain("formatAssistantActivityElapsed");
    expect(animationSource).not.toContain("assistantThinkingEvent__elapsed");
    expect(animationSource).not.toContain("is switching to");
    expect(stylesSource).not.toContain("assistantThinkingEvent__elapsed");
    expect(animationSource).not.toContain("tokens");
    expect(animationSource).toContain("assistantWorking");
    expect(animationSource).toContain("assistantWorkingEvent");
    expect(animationSource).toContain("assistantStopActive");
    expect(animationSource).toContain('kind: "stop_assistant"');
    expect(animationSource).toContain("Stop assistant");
    expect(animationSource).toContain("composer__send--stop");
    expect(animationSource).toContain("disabled={!canSend && !assistantStopActive}");
    expect(mainSource).toContain("interface AssistantRunControl");
    expect(mainSource).toContain("stopActiveAssistantRunControl");
    expect(mainSource).toContain("throwIfAssistantRunCancelled");
    expect(mainSource).toContain('text: "Stopped by user."');
  });

  it("injects the full local action atlas at boot and keeps per-turn reminders compact", () => {
    expect(mainSource).toContain("function shouldInjectFullAgentActionManifest");
    expect(mainSource).toContain("function shouldInjectCompactAgentActionManifest");
    expect(mainSource).toContain("function agentActionContinuationManifest");
    expect(mainSource).toContain("function brainRuntimeReminderManifest");
    expect(mainSource).toContain("function ingenLoopActionRhythmManifest");
    expect(mainSource).toContain("INGEN_LOOP_ACTION_RHYTHM v1");
    expect(mainSource).toContain("default_mode=loop_stream_chunked");
    expect(mainSource).toContain("direct_answer_exception=Only trivial answer-only turns");
    expect(mainSource).toContain("chunking=Stream useful visible progress in compact chunks");
    expect(mainSource).toContain("action_boundary=Every Brain CodeAct from every active/injected Brain");
    expect(mainSource).toContain("function ingenProviderRuntimeContract");
    expect(mainSource).toContain("INGEN_PROVIDER_RUNTIME_CONTRACT v1");
    expect(mainSource).toContain("provider: \"codex\"");
    expect(mainSource).toContain("provider: \"claude\"");
    expect(mainSource).toContain("provider: \"openrouter\"");
    expect(mainSource).toContain("LOCAL_ACTION_ATLAS_BOOT v1");
    expect(mainSource).toContain("full local action atlas is injected at session boot and after conversation compaction only");
    expect(mainSource).toContain("boot_manifest=already_injected_once_for_this_session_or_reinjected_after_compaction");
    expect(mainSource).toContain("local_actions_codeact=");
    expect(mainSource).toContain("executeAssistantLocalActionsCodeAct");
    expect(mainSource).toContain("LOCAL_ACTIONS_RESULT");
    expect(mainSource).toContain("manifest.runtime.manifestHash");
    expect(mainSource).toContain("manifest.runtime.atlasHash");
    expect(mainSource).toContain("delta_policy=${manifest.runtime.injectionPolicy}");
    expect(mainSource).toContain("prompt_budget=${manifest.runtime.promptBudget}");
    expect(mainSource).toContain("token_estimate_compact=${manifest.runtime.promptTokenEstimate.compactContinuation}");
    expect(mainSource).toContain("installed_tools_delta=${manifest.runtime.installedToolIds.join(\"|\")}");
    expect(mainSource).toContain("missing_tools_delta=${manifest.runtime.missingToolIds.join(\"|\")}");
    expect(mainSource).toContain("selected_capability_policy=Use AGENT_ACTION_SELECTED_CAPABILITY");
    expect(mainSource).toContain("textLooksLikeLocalActionIntent(userText)");
    expect(mainSource).toContain("textIsAgentActionContinuation(userText)");
    expect(mainSource).toContain("transcriptHasRecentAgentActionLoop(transcript)");
    expect(mainSource).toContain("shouldInjectFullAgentActionManifest(userText, transcript)");
    expect(mainSource).toContain("shouldInjectCompactAgentActionManifest(userText, transcript)");
    expect(mainSource).toContain("full_atlas_location=brain_boot_manifest_or_post_compaction_reinjection");
    expect(mainSource).toContain("agentActionContinuationManifest()");
    expect(mainSource).toContain("[agentActionRoutingHint(), agentActionContinuationManifest()].join(\"\\n\")");
    expect(mainSource).toContain("ingenProviderRuntimeContract({");
    expect(mainSource).not.toContain("return [agentActionRoutingHint(), agentActionHostPromptManifest(agentActionHostConfig())].join(\"\\n\")");
    expect(mainSource).toContain(": \"\"");
    expect(mainSource).toContain("agentActionContextManifest(userText, transcript)");
  });

  it("keeps Brain CodeActs inside the agentic loop instead of final chatbot prose", () => {
    expect(mainSource).toContain("const BRAIN_CODEACT_COMMANDS_BY_LENGTH");
    expect(mainSource).toContain("function brainCodeActCommandsFromAssistantText");
    expect(mainSource).toContain("function isBrainCodeActUserPauseCommand");
    expect(mainSource).toContain("function isBrainCodeActSurfaceCommand");
    expect(mainSource).toContain("function shouldContinueAfterBrainCodeAct");
    expect(mainSource).toContain("function brainCodeActLoopContinuationUserText");
    expect(mainSource).toContain("interface UniversalLoopOrchestratorPassResult");
    expect(mainSource).toContain("async function executeUniversalLoopOrchestratorPass");
    expect(mainSource).toContain("function universalLoopContinuationUserText");
    expect(mainSource).toContain("function universalLoopContinuationKey");
    expect(mainSource).toContain("async function executeUniversalLoopContinuation");
    expect(mainSource).toContain("const seenContinuationKeys = new Set<string>()");
    expect(mainSource).toContain("while (true)");
    expect(mainSource).toContain("if (seenContinuationKeys.has(continuationKey))");
    expect(mainSource).toContain("pass = continuationPass");
    expect(mainSource).toContain("BRAIN_CODEACT_LOOP_CONTINUATION v1");
    expect(mainSource).toContain("agentLoopNarrationContractManifest()");
    expect(mainSource).toContain("visible_step_shape=Each visible paragraph should make the step understandable");
    expect(mainSource).toContain("event_coupling=When you say an action will be taken");
    expect(mainSource).toContain("previous_visible_progress=");
    expect(mainSource).toContain("assistant-response-${Date.now()}-${continuation.idSuffix}");
    expect(mainSource).toContain("command === BRAIN_QUESTIONNAIRE_COMMAND");
    expect(mainSource).toContain("command === BRAIN_WORKSPACE_COMMAND");
    expect(mainSource).toContain("searchArchiveActive: Boolean(searchArchiveCodeAct)");
    expect(mainSource).toContain("const orchestratorPass = await executeUniversalLoopOrchestratorPass({");
    expect(mainSource).toContain("nextTranscript = await executeUniversalLoopContinuation({");
    expect(mainSource).toContain("shouldContinueAfterBrainCodeAct({");
    expect(mainSource).toContain("const continuationPass = await executeUniversalLoopOrchestratorPass({");
    expect(mainSource).toContain("archiveTranscriptMessage(params.session, continuationPass.assistantMessage)");
    expect(mainSource).not.toContain("continuationMessage = await executeAssistantAgentActionLoop({");
  });

  it("renders domain Brain CodeActs with the blue Brain event treatment", () => {
    expect(animationSource).toContain("BRAIN_NEWBRAIN_COMMAND");
    expect(animationSource).toContain("BRAIN_MODIFY_NAMED_BRAIN_COMMAND");
    expect(animationSource).toContain('const NEW_BRAIN_EVENT_VERBS = ["created", "added", "prepared", "initialized", "registered"]');
    expect(animationSource).toContain('const MODIFY_BRAIN_EVENT_VERBS = ["modified", "updated", "refined", "adjusted", "revised"]');
    expect(animationSource).toContain("function stableEventVariantIndex");
    expect(animationSource).toContain("function newBrainNameFromLine");
    expect(animationSource).toContain("function modifyNamedBrainNameFromLine");
    expect(animationSource).toContain("function domainBrainEventText");
    expect(animationSource).toContain('`New "${name}" Brain ${verb}`');
    expect(animationSource).toContain("`${name} ${verb}`");
    expect(animationSource).toContain("/^\\/modify(?:\"[^\"]+\"|'[^']+')brain_$/.test(trimmed)");
    expect(animationSource).toContain("/\\/modify(?:\"[^\"]+\"|'[^']+')brain_/.test(trimmed)");
    expect(animationSource).toContain("function isBrainStyledCommand");
    expect(animationSource).toContain("command === BRAIN_NEWBRAIN_COMMAND || command === BRAIN_MODIFY_NAMED_BRAIN_COMMAND");
    expect(animationSource).toContain('<BrainSegmentCodeActIcon phase="changed" />');
    expect(animationSource).toContain("transcriptCodeActEvent--brainSegment");
  });

  it("gives non-Brain CodeAct events a working and completed visual phase", () => {
    expect(animationSource).toContain("const isGenericCodeActEvent = !isBrainStyled && !agentCommand");
    expect(animationSource).toContain('useState<"working" | "complete">');
    expect(animationSource).toContain("setGenericCodeActPhase(\"working\")");
    expect(animationSource).toContain("setGenericCodeActPhase(\"complete\")");
    expect(animationSource).toContain("transcriptCodeActEvent--codeact-${genericCodeActPhase}");
    expect(stylesSource).toContain(".transcriptCodeActEvent--codeact-working");
    expect(stylesSource).toContain(".transcriptCodeActEvent--codeact-working .transcriptCodeActEvent__icon");
    expect(stylesSource).toContain(".transcriptCodeActEvent--codeact-complete");
    expect(stylesSource).toContain(".transcriptCodeActEvent--codeact-complete .transcriptCodeActEvent__text");
    expect(stylesSource).toContain(".transcriptCodeActEvent--codeact-working .transcriptCodeActEvent__icon");
    expect(stylesSource).toContain(".transcriptCodeActEvent--codeact-complete,");
  });

  it("keeps loop continuation results compact before reinjection", () => {
    expect(mainSource).toContain("const AGENT_ACTION_RESULT_ITEM_LIMIT = 10");
    expect(mainSource).toContain("const AGENT_ACTION_RESULT_MATCH_LIMIT = 8");
    expect(mainSource).toContain("const AGENT_ACTION_RESULT_PREVIEW_BYTES = 6_000");
    expect(mainSource).toContain("function compactAgentActionItems");
    expect(mainSource).toContain("function compactAgentActionMatches");
    expect(mainSource).toContain("omittedItems");
    expect(mainSource).toContain("omittedMatches");
    expect(mainSource).toContain("trimUtf8Bytes(result.stdoutPreview, AGENT_ACTION_RESULT_PREVIEW_BYTES)");
  });

  it("has diagnostics for desktop organization, tool-result resumption, compaction, and event/prompt separation", () => {
    expect(mainSource).toContain("function deterministicOrganizationRequestsFromList");
    expect(mainSource).toContain("function agentActionFileOrganizationRequests");
    expect(mainSource).toContain("AGENT_ACTION_VISIBLE_SHORTCUT_EXTENSIONS");
    expect(mainSource).toContain("AGENT_ACTION_DEFAULT_COLLECTION_FOLDER_NAME");
    expect(mainSource).toContain("AGENT_ACTION_DETERMINISTIC_STEP_DELAY_MS");
    expect(mainSource).toContain("function agentActionShouldLeavePathInPlace");
    expect(mainSource).toContain("function agentActionFileOrganizationProgressText");
    expect(mainSource).toContain("function agentActionFileOrganizationFinalText");
    expect(mainSource).toContain("await waitAgentActionVisualStep()");
    expect(mainSource).toContain("ACTION_NARRATION_CONTRACT v1");
    expect(mainSource).toContain("pedagogy=Name pivots and tradeoffs plainly");
    expect(mainSource).toContain("evidence=After a tool result, mention the runtime proof that matters");
    expect(mainSource).toContain("I am starting the sorting pass with the most obvious items.");
    expect(mainSource).toContain("I am moving ${sourceName} to ${targetFolder}");
    expect(mainSource).not.toContain("Etape ${index + 1}/${total}");
    expect(mainSource).not.toContain("sans toucher aux raccourcis d'application");
    expect(mainSource).toContain("agentActionOrganizeCategory(item)");
    expect(mainSource).toContain("action: \"create_directory\"");
    expect(mainSource).toContain("action: \"move_path\"");
    expect(mainSource).toContain("agentActionStepNeedsMutationFollowUp(params.originalUserText, extracted.request, result)");
    expect(mainSource).toContain("agentActionLoopContinuationUserText(params.originalUserText, extracted.request, result, step)");
    expect(mainSource).toContain("function agentActionFailureContinuationUserText");
    expect(mainSource).toContain("runtime_next=The last local action failed or was refused");
    expect(mainSource).toContain("blocked_policy=If the error proves a protected root");
    expect(mainSource).toContain("control_line=If a safe alternative exists");
    expect(mainSource).toContain("agentActionLoopFailureContinuationStep");
    expect(mainSource).toContain("AGENT_ACTION_RESULT_PREFIX");
    expect(mainSource).toContain("compactAgentActionResult(result)");
    expect(mainSource).not.toContain("Style de progression:");
    expect(mainSource).not.toContain("Pour ranger/organiser un bureau");
    expect(mainSource).not.toContain("Pour organiser un bureau");
    expect(mainSource).not.toContain("AGENT_ACTION_LOOP_DEFAULT_MAX_STEPS");
    expect(mainSource).not.toContain("AGENT_ACTION_LOOP_FILE_MUTATION_MAX_STEPS");
    expect(mainSource).not.toContain("function agentActionLoopMaxStepsForObjective");
    expect(mainSource).toContain("function agentActionShouldRunFileOrganizationFallback");
    expect(mainSource).not.toContain("La limite de boucle approche");
    expect(mainSource).not.toContain("No further action was executed after this guard fired.");
    expect(mainSource).toContain("function agentActionSelectedCapabilityContext");
    expect(mainSource).toContain("agentActionCapabilityDetailManifest(agentActionHostConfig(), capabilityId)");
    expect(mainSource).toContain("AGENT_ACTION_COMPACTION_STATE v1");
    expect(mainSource).toContain("last_tool_ground_truth=");
    expect(mainSource).toContain("After compaction, continue the same observe-act-verify-retry loop");
    expect(normalizedMainSource).toContain("result.accepted\n      ? \"next=verify whether the user objective is now satisfied");
    expect(mainSource).toContain("agentActionSelectedCapabilityContext(request, result)");
    expect(normalizedMainSource).toContain("agentEvents.emit({\n      kind: \"compaction_started\"");
    expect(normalizedMainSource).toContain("agentEvents.emit({\n      kind: \"compaction_completed\"");
    expect(mainSource).toContain("window.webContents.send(\"forge:agent-runtime-event\", runtimeEvent)");
    expect(mainSource).toContain("!message.id.startsWith(\"assistant-status-\")");
    expect(mainSource).not.toContain("providerConversationMessages(\n  event");
  });

  it("uses a universal action-loop state instead of the desktop fallback as the normal path", () => {
    expect(ipcContractSource).toContain('schema: "ingen.agent_action_loop.state.v1"');
    expect(ipcContractSource).toContain("export type AgentActionLoopOutcome");
    expect(ipcContractSource).toContain("export interface AgentActionLoopState");
    expect(mainSource).toContain("type AgentActionLoopState");
    expect(mainSource).toContain("const AGENT_ACTION_COMPAT_DETERMINISTIC_FALLBACK");
    expect(mainSource).toContain("function createAgentActionLoopState");
    expect(mainSource).toContain("function agentActionLoopWithResult");
    expect(mainSource).toContain("function agentActionLoopWithStatus");
    expect(mainSource).toContain("function reportableAgentActionLoopOutcome");
    expect(mainSource).toContain("function ensureAgentActionLoopFinalSummary");
    expect(mainSource).toContain("Final summary: agent loop ${state.finalStatus}");
    expect(mainSource).toContain("AGENT_ACTION_COMPAT_DETERMINISTIC_FALLBACK &&");
    expect(mainSource).not.toContain("AGENT_ACTION_COMPAT_DETERMINISTIC_FALLBACK || agentActionShouldRunFileOrganizationFallback");
    expect(mainSource).not.toContain("Final summary: agent loop max_steps");
    expect(mainSource).toContain("while (true)");
    expect(mainSource).toContain("stopActiveAssistantRunControl");
    expect(mainSource).toContain('case "stop_assistant"');
    expect(mainSource).toContain('outcome: reportableAgentActionLoopOutcome(loopState, "blocked")');
    expect(mainSource).not.toContain('outcome: "deterministic_fallback"');
  });

  it("keeps filesystem move events separate from file content edit counters", () => {
    expect(animationSource).toContain("function isAgentFileModificationCommand");
    expect(animationSource).toContain("return command === AGENT_COPY_PATH_COMMAND");
    expect(animationSource).toContain("return delta.addedChars > 0 || delta.removedChars > 0 ? delta : undefined");
    expect(animationSource).toContain("is applying a local action");
    expect(animationSource).not.toContain("is using ${command}");
    expect(animationSource).toContain("Modified");
    expect(animationSource).not.toContain("Modification de");
  });

  it("keeps shell payloads out of the readable assistant transcript", () => {
    expect(animationSource).toContain("function isShellPayloadLine");
    expect(animationSource).toContain("isShellCodeActCommand(lastEvent?.command)");
    expect(animationSource).toContain("lastEvent.detail = shellPayloadDisplayText(line)");
    expect(animationSource).toContain("Copy-Item|ConvertTo-Json|ForEach-Object|Get-ChildItem");
  });
});
