import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const routerSource = readFileSync("src/renderer/HeaderSurfaceRouter.tsx", "utf8");
const appSource = readFileSync("src/renderer/App.tsx", "utf8");
const canvasSurfacesSource = readFileSync("src/renderer/CanvasSurfacesSlice.tsx", "utf8");
const stylesSource = readFileSync("src/renderer/styles.css", "utf8");
const launcherSource = readFileSync("run_ingen_electron_shell.cmd", "utf8");
const mainSource = readFileSync("src/main/main.ts", "utf8");
const viteConfigSource = readFileSync("vite.config.ts", "utf8");
const rustBackendSource = readFileSync("src/main/rust-backend.ts", "utf8");
const nativeBridgeSource = readFileSync("../ingen_native_services/src/bin/ingen_electron_backend_bridge.rs", "utf8");

describe("Banger native viewport contract", () => {
  it("keeps the Banger page as a full-screen native render surface with no inner frame prose", () => {
    expect(routerSource).toContain('"--surface-left": "0px"');
    expect(routerSource).toContain('"--surface-top": "0px"');
    expect(routerSource).toContain('"--surface-width": "100vw"');
    expect(routerSource).toContain('"--surface-height": "100vh"');
    expect(routerSource).toContain("getBangerPresentLoopBootstrap");
    expect(routerSource).toContain('sceneKind: "maps_sphere"');
    expect(routerSource).toContain("presentLoop.previewFrameDataUrl");
    expect(routerSource).toContain("rust_banger_wgpu_maps_sphere_present_loop_rgba8_to_bmp_data_url");
    expect(routerSource).toContain('"nativeViewportSlot nativeViewportSlot--live"');
    expect(routerSource).toContain("bangerSphereNativeFrame__fallback");
    expect(routerSource).toContain('data-native-contract={surface.nativeContract}');
    expect(routerSource).toContain('data-present-loop={presentLoop?.routeStatus ?? "pending"}');
    expect(routerSource).not.toContain("BangerPreviewFrameResult");
    expect(routerSource).not.toContain("native raster frame loading");
  });

  it("keeps the Banger page and Maps viewer on native render paths", () => {
    expect(routerSource).not.toContain('from "cesium"');
    expect(routerSource).not.toContain('import("cesium")');
    expect(routerSource).not.toContain("new Cesium.Viewer");
    expect(routerSource).not.toContain("getBangerGoogleTilesConfig");
    expect(canvasSurfacesSource).not.toContain('import("cesium")');
    expect(canvasSurfacesSource).not.toContain("new Cesium.Viewer");
    expect(canvasSurfacesSource).not.toContain("Cesium.GoogleMaps.mapTilesApiEndpoint");
    expect(canvasSurfacesSource).not.toContain("Cesium.createGooglePhotorealistic3DTileset");
    expect(canvasSurfacesSource).not.toContain("onlyUsingWithGoogleGeocoder");
    expect(canvasSurfacesSource).not.toContain("resolveCesiumIonAccessToken");
    expect(canvasSurfacesSource).not.toContain("Cesium.Ion.defaultAccessToken");
    expect(canvasSurfacesSource).not.toContain("showCreditsOnScreen");
    expect(canvasSurfacesSource).not.toContain("Banger Maps Cesium tileset failed.");
    expect(canvasSurfacesSource).not.toContain("Google Map Tiles direct mode requires GOOGLE_MAP_TILES_API_KEY.");
    expect(viteConfigSource).not.toContain("vite-plugin-cesium");
    expect(viteConfigSource).not.toContain("cesium()");
    expect(canvasSurfacesSource).toContain("BangerMapsNativeViewport");
    expect(canvasSurfacesSource).toContain("showNativeMaps");
    expect(canvasSurfacesSource).toContain("updateNativeMapsBounds");
    expect(canvasSurfacesSource).toContain("Banger native Maps surface live");
    expect(canvasSurfacesSource).not.toContain("GOOGLE_MAPS_PROXY_KEY_ALIAS");
    expect(canvasSurfacesSource).not.toContain("falling back to native sphere");
    expect(stylesSource).not.toContain(".bangerMapsCesiumViewport");
    expect(stylesSource).not.toContain(".cesium-widget");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot::after");
    expect(stylesSource).toContain("content: none");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot--live");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallback");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).not.toContain("transparent 0 12%");
    expect(stylesSource).not.toContain("#1a9eb6 0 9%");
    expect(stylesSource).toContain("object-fit: cover");
  });

  it("launches the Rust native child-surface host instead of only probing offscreen", () => {
    expect(rustBackendSource).toContain("launchRustBangerNativeHost");
    expect(rustBackendSource).toContain("--banger-native-host");
    expect(rustBackendSource).toContain("FORGE_BANGER_PARENT_HWND");
    expect(rustBackendSource).toContain("shaderSourceHash");
    expect(rustBackendSource).toContain("renderPipelineHash");
    expect(rustBackendSource).toContain("bangerPreviewRgba8ToBmpDataUrl");
    expect(rustBackendSource).toContain("falling back to offscreen present-loop preview");
    expect(rustBackendSource).toContain("renderLoopPolicy");
    expect(rustBackendSource).toContain("indexCount");
    expect(rustBackendSource).toContain("instanceCount");
    expect(rustBackendSource).toContain("sceneObjectCount");
    expect(rustBackendSource).toContain("sceneGraphHash");
    expect(rustBackendSource).toContain("instanceBufferHash");
    expect(rustBackendSource).toContain("sceneMeshHash");
    expect(rustBackendSource).toContain("cameraUniformHash");
    expect(rustBackendSource).toContain("frameTargetPolicy");
    expect(rustBackendSource).toContain("frameTargetHash");
    expect(rustBackendSource).toContain("frameTargetAllocationCount");
    expect(nativeBridgeSource).toContain("Depth24Plus");
    expect(nativeBridgeSource).toContain("draw_indexed");
    expect(nativeBridgeSource).toContain("0..scene_pipeline.instance_count");
    expect(nativeBridgeSource).toContain("VertexStepMode::Instance");
    expect(nativeBridgeSource).toContain("banger_scene_instance_bytes");
    expect(nativeBridgeSource).toContain("banger_cube_vertex_bytes");
    expect(nativeBridgeSource).toContain("BangerNativeFrameTarget");
    expect(nativeBridgeSource).toContain("create_banger_frame_target");
    expect(nativeBridgeSource).toContain("persistent_resize_tracked_depth_target_v1");
    expect(nativeBridgeSource).toContain("forge.banger.maps_photorealistic_3d_tiles_contract.v1");
    expect(nativeBridgeSource).toContain("google_photorealistic_3d_tiles");
    expect(nativeBridgeSource).toContain("Cesium3DTileset_style_native_streamer");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_streamer.v1");
    expect(nativeBridgeSource).toContain("--banger-maps-root-ingest");
    expect(nativeBridgeSource).toContain("--banger-maps-content-cache");
    expect(nativeBridgeSource).toContain("--banger-maps-content-decode");
    expect(nativeBridgeSource).toContain("--banger-maps-gpu-stage");
    expect(nativeBridgeSource).toContain("--banger-maps-native-render-gate");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_root_ingest.v1");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_content_cache.v1");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_content_decode.v1");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_gpu_staging.v1");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_render_gate.v1");
    expect(nativeBridgeSource).toContain("VERTEX|COPY_DST");
    expect(nativeBridgeSource).toContain("INDEX|COPY_DST");
    expect(nativeBridgeSource).toContain("TEXTURE_BINDING|COPY_DST");
    expect(nativeBridgeSource).toContain("upload_banger_maps_gltf_payload_to_wgpu");
    expect(nativeBridgeSource).toContain("banger_maps_render_mesh_from_gltf");
    expect(nativeBridgeSource).toContain("banger_maps_3d_tiles_gltf_first_primitive");
    expect(nativeBridgeSource).toContain("KHR_draco_mesh_compression");
    expect(nativeBridgeSource).toContain("EXT_meshopt_compression");
    expect(nativeBridgeSource).toContain("google_tiles_entitlement_or_region_blocked");
    expect(nativeBridgeSource).toContain("FORGE_BANGER_MAPS_ROOT_URL");
    expect(nativeBridgeSource).toContain("FORGE_BANGER_TILE_CACHE_DIR");
    expect(nativeBridgeSource).toContain("FORGE_BANGER_MAPS_FETCH_TILE_CONTENT");
    expect(nativeBridgeSource).toContain("FORGE_BANGER_MAPS_CONTENT_FETCH_LIMIT");
    expect(nativeBridgeSource).toContain("FORGE_BANGER_MAPS_DECODE_TILE_CONTENT");
    expect(nativeBridgeSource).toContain("BangerMapsRootIngestProjection");
    expect(nativeBridgeSource).toContain("BangerMapsTraversalSeed");
    expect(nativeBridgeSource).toContain("BangerMapsTraversalTile");
    expect(nativeBridgeSource).toContain("BangerMapsContentCacheProjection");
    expect(nativeBridgeSource).toContain("BangerMapsContentCacheRecord");
    expect(nativeBridgeSource).toContain("BangerMapsContentDecodeProjection");
    expect(nativeBridgeSource).toContain("BangerB3dmHeaderProjection");
    expect(nativeBridgeSource).toContain("BangerGlbProjection");
    expect(nativeBridgeSource).toContain("BangerGltfSummaryProjection");
    expect(nativeBridgeSource).toContain("reqwest::blocking::Client");
    expect(nativeBridgeSource).toContain("traversal_seed_hash");
    expect(nativeBridgeSource).toContain("forge.banger.native_3d_tiles_traversal_seed.v1");
    expect(nativeBridgeSource).toContain("parent_first_screen_space_error_seed");
    expect(nativeBridgeSource).toContain("FORGE_BANGER_MAPS_TRAVERSAL_MAX_TILES");
    expect(nativeBridgeSource).toContain("3d_tiles_root_json_manifest_ingestion");
    expect(nativeBridgeSource).toContain("b3dm_glb_gltf_mesh_material_texture_decode");
    expect(nativeBridgeSource).toContain("wgs84_ecef_to_enu_floating_origin");
    expect(nativeBridgeSource).toContain("tile_content_or_gltf_upload_required_before_visible_maps_draw");
    expect(nativeBridgeSource).toContain("none_direct_tiles_required");
    expect(nativeBridgeSource).toContain("CesiumGeoreference_style_floating_origin");
    expect(nativeBridgeSource).toContain("screen_space_error");
    expect(nativeBridgeSource).toContain("visible_on_screen");
    expect(mainSource).toContain("CESIUM_ACCESS_TOKEN");
    expect(mainSource).toContain("cesium-ion-direct");
    expect(mainSource).toContain("google-map-tiles-direct");
    expect(mainSource).toContain("google-map-tiles-api-key");
    expect(mainSource).toContain("none_direct_cesium_required");
    expect(mainSource).toContain("cesium_or_google_direct_credentials_required");
    expect(mainSource).not.toContain("render-resolver-proxy");
    expect(mainSource).not.toContain("render-proxy");
  });

  it("paints Maps from the Banger native sphere host and forbids CesiumJS/WebGL regressions", () => {
    expect(canvasSurfacesSource).toContain("BangerMapsNativeViewport");
    expect(canvasSurfacesSource).not.toContain("getBangerPreviewFrame");
    expect(canvasSurfacesSource).toContain("getBangerGoogleTilesConfig");
    expect(canvasSurfacesSource).not.toContain("BangerMapsCesiumViewport");
    expect(canvasSurfacesSource).not.toContain("Cesium photorealistic tiles bootstrap");
    expect(canvasSurfacesSource).not.toContain("Cesium ion direct loading Google photorealistic 3D Tiles");
    expect(canvasSurfacesSource).not.toContain("config.accessMode !== \"google-map-tiles-api-key\"");
    expect(canvasSurfacesSource).not.toContain("googleMapsApiKeyFromRootTilesetUrl");
    expect(canvasSurfacesSource).not.toContain("Google Map Tiles direct mode requires GOOGLE_MAP_TILES_API_KEY.");
    expect(canvasSurfacesSource).not.toContain("Cesium Google photorealistic 3D Tiles live");
    expect(canvasSurfacesSource).not.toContain("Cesium direct tiles still loading");
    expect(canvasSurfacesSource).not.toContain("googleMapsEndpointFromRootTilesetUrl");
    expect(canvasSurfacesSource).toContain("showNativeMaps");
    expect(canvasSurfacesSource).toContain("updateNativeMapsBounds");
    expect(canvasSurfacesSource).toContain("hideNativeMaps");
    expect(canvasSurfacesSource).toContain("Banger native Maps surface live");
    expect(canvasSurfacesSource).toContain("data-tileset-provider");
    expect(canvasSurfacesSource).toContain("data-tileset-renderer-model");
    expect(canvasSurfacesSource).toContain("data-tileset-georeference");
    expect(canvasSurfacesSource).toContain("data-tileset-lod");
    expect(canvasSurfacesSource).toContain("data-native-streamer");
    expect(canvasSurfacesSource).toContain("data-native-streamer-status");
    expect(canvasSurfacesSource).toContain("data-native-streamer-blocker");
    expect(canvasSurfacesSource).toContain("redactedTilesetEndpoint");
    expect(canvasSurfacesSource).not.toContain("bangerMapsCesiumViewport--error");
    expect(canvasSurfacesSource).not.toContain("bangerMapsCesiumViewport__error");
    expect(canvasSurfacesSource).not.toContain("previewFrameDataUrl");
    expect(canvasSurfacesSource).not.toContain("bangerSphereNativeFrame__preview");
    expect(canvasSurfacesSource).toContain("bangerSphereNativeFrame__fallback");
    expect(canvasSurfacesSource).toContain("bangerSphereNativeFrame__fallbackSphere");
    expect(canvasSurfacesSource).toContain('aria-label={`${label} - ${tilesConfigLoaded ? status : "Banger native Maps config loading"}`}');
    expect(canvasSurfacesSource).not.toContain('<span className="webExplorerNativeStatus">{label} - {status}</span>');
    expect(stylesSource).toContain(".bangerSphereNativeFrame__preview");
    expect(stylesSource).toContain(".bangerSphereNativeFrame");
    expect(stylesSource).toContain("pointer-events: none");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("width: var(--transcript-media-width)");
    expect(stylesSource).toContain("height: var(--transcript-media-flow-height)");
    expect(stylesSource).toContain("right: var(--transcript-media-right-gap)");
    expect(stylesSource).toContain("overflow: visible");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame");
    expect(stylesSource).toContain("inset: 50% auto auto 59%");
    expect(stylesSource).toContain("width: min(86.89173795355475vw, 107.86560573544727vh, 1139.0766445892043px)");
    expect(stylesSource).toContain("height: min(86.89173795355475vw, 107.86560573544727vh, 1139.0766445892043px)");
    expect(stylesSource).toContain("transform: translate3d(-50%, -50%, 0)");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__preview");
    expect(stylesSource).toContain("object-fit: contain");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__fallback");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .parallelCanvasClose");
    expect(stylesSource).toContain("display: none");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .webExplorerClose");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).toContain("width: min(100%, 1139.0766445892043px)");
    expect(appSource).toContain("canvasMapsClosing");
    expect(appSource).toContain("canvasPlanetsOpen || canvasMapsOpen || canvasMapsClosing");
    expect(appSource).toContain("closeCanvasMaps();");
    expect(appSource).toContain("mapsViewportTarget");
    expect(appSource).toContain("setMapsViewportTarget");
    expect(appSource).toContain("latitude: typeof event.latitude === \"number\" ? event.latitude : undefined");
    expect(appSource).toContain("mapsTarget={mapsViewportTarget}");
    expect(canvasSurfacesSource).toContain('mapsClosing ? "canvasSurfaces--mapsClosing" : ""');
    expect(stylesSource).toContain(".navIconButton--selected .shellIcon--nav-web");
    expect(stylesSource).toContain(".canvasSurfaces--mapsClosing .mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("animation: mapsSphereRailExit 260ms");
    expect(stylesSource).toContain("@keyframes mapsSphereRailExit");
    expect(stylesSource).toContain(".shell--maps-canvas-open .transcriptTextFrame");
    expect(stylesSource).toContain("var(--transcript-media-avoidance-width)");
    expect(stylesSource).toContain("object-fit: cover");
    expect(mainSource).toContain("provider: \"google_photorealistic_3d_tiles\"");
    expect(mainSource).toContain("rendererModel: \"cesium_for_unreal_style_3d_tileset\"");
    expect(mainSource).toContain("directRootTilesetEndpoint: \"https://tile.googleapis.com/v1/3dtiles/root.json\"");
    expect(mainSource).toContain("accessMode: \"cesium-ion\"");
    expect(mainSource).toContain("accessMode: \"google-map-tiles-api-key\"");
    expect(mainSource).not.toContain("accessMode: \"render-proxy\"");
    expect(mainSource).toContain("source: \"cesium-ion-token-broker\"");
    expect(mainSource).toContain("FORGE_BANGER_CESIUM_ION_TOKEN_URL");
    expect(mainSource).toContain("/api/banger/cesium-ion-token");
    expect(canvasSurfacesSource).not.toContain("config.cesiumIonAccessTokenUrl");
    expect(mainSource).not.toContain("FORGE_BANGER_GOOGLE_TILES_BACKEND_URL");
    expect(mainSource).toContain("rootRequestTtlHours: 3");
    expect(mainSource).toContain("showCreditsOnScreen: true");
    expect(mainSource).toContain("policy: \"screen_space_error\"");
    expect(mainSource).toContain("authority: \"banger_tileset_residency_cache\"");
    expect(mainSource).toContain("nativeStreamer");
    expect(mainSource).toContain("meshlet_or_indexed_mesh_upload_pending");
  });

  it("rebuilds stale Electron renderer assets before reusing the desktop fast path", () => {
    expect(launcherSource).toContain("preload.cjs");
    expect(launcherSource).toContain("ingen-electron-launch-build-%WORKSPACE_BUILD_ID%.lock");
    expect(launcherSource).toContain("set DESKTOP_AUTO_REBUILD=1");
    expect(launcherSource).toContain("FORGE_ELECTRON_DESKTOP_STABLE");
    expect(launcherSource).toContain("if errorlevel 1 set NEED_ELECTRON_REBUILD=1");
    expect(launcherSource).toContain('if "%NEED_ELECTRON_REBUILD%"=="0" (');
    expect(launcherSource).toContain("Preparing freshness checks without interrupting the active window");
    expect(launcherSource).toContain("Build work will prepare the latest master output before the active app is touched.");
    expect(launcherSource).toContain("Active InGen window detected. Sending live master renderer URL");
    expect(launcherSource).toContain("Active InGen window is running old main/native code. Restarting it after the fresh master output is ready.");
  });
});
