import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const routerSource = readFileSync("src/renderer/HeaderSurfaceRouter.tsx", "utf8");
const appSource = readFileSync("src/renderer/App.tsx", "utf8");
const canvasSurfacesSource = readFileSync("src/renderer/CanvasSurfacesSlice.tsx", "utf8");
const stylesSource = readFileSync("src/renderer/styles.css", "utf8");
const launcherSource = readFileSync("run_ingen_electron_shell.cmd", "utf8");
const mainSource = readFileSync("src/main/main.ts", "utf8");
const rustBackendSource = readFileSync("src/main/rust-backend.ts", "utf8");
const nativeBridgeSource = readFileSync("../ingen_native_services/src/bin/ingen_electron_backend_bridge.rs", "utf8");

describe("Banger native viewport contract", () => {
  it("keeps the Banger page as a full-screen native render surface with no inner frame prose", () => {
    expect(routerSource).toContain('"--surface-left": "0px"');
    expect(routerSource).toContain('"--surface-top": "0px"');
    expect(routerSource).toContain('"--surface-width": "100vw"');
    expect(routerSource).toContain('"--surface-height": "100vh"');
    expect(routerSource).toContain("getBangerPresentLoopBootstrap");
    expect(routerSource).toContain('sceneKind: "maps_sphere"');
    expect(routerSource).toContain("presentLoop.previewFrameDataUrl");
    expect(routerSource).toContain("rust_banger_wgpu_maps_sphere_present_loop_rgba8_to_bmp_data_url");
    expect(routerSource).toContain('"nativeViewportSlot nativeViewportSlot--live"');
    expect(routerSource).toContain("bangerSphereNativeFrame__fallback");
    expect(routerSource).toContain('data-native-contract={surface.nativeContract}');
    expect(routerSource).toContain('data-present-loop={presentLoop?.routeStatus ?? "pending"}');
    expect(routerSource).not.toContain("BangerPreviewFrameResult");
    expect(routerSource).not.toContain("native raster frame loading");
  });

  it("keeps the Banger page native while allowing Cesium only in the Maps viewer", () => {
    expect(routerSource).not.toContain('from "cesium"');
    expect(routerSource).not.toContain('import("cesium")');
    expect(routerSource).not.toContain("new Cesium.Viewer");
    expect(routerSource).not.toContain("getBangerGoogleTilesConfig");
    expect(canvasSurfacesSource).toContain('import("cesium")');
    expect(canvasSurfacesSource).toContain("new Cesium.Viewer");
    expect(canvasSurfacesSource).toContain("Cesium.Cesium3DTileset.fromUrl");
    expect(canvasSurfacesSource).toContain("showCreditsOnScreen");
    expect(canvasSurfacesSource).toContain("Banger Maps Cesium tileset failed; falling back to native sphere.");
    expect(stylesSource).toContain(".bangerMapsCesiumViewport");
    expect(stylesSource).toContain(".bangerMapsCesiumViewport .cesium-widget-credits");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot::after");
    expect(stylesSource).toContain("content: none");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot--live");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallback");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).not.toContain("transparent 0 12%");
    expect(stylesSource).not.toContain("#1a9eb6 0 9%");
    expect(stylesSource).toContain("object-fit: cover");
  });

  it("launches the Rust native child-surface host instead of only probing offscreen", () => {
    expect(rustBackendSource).toContain("launchRustBangerNativeHost");
    expect(rustBackendSource).toContain("--banger-native-host");
    expect(rustBackendSource).toContain("FORGE_BANGER_PARENT_HWND");
    expect(rustBackendSource).toContain("shaderSourceHash");
    expect(rustBackendSource).toContain("renderPipelineHash");
    expect(rustBackendSource).toContain("bangerPreviewRgba8ToBmpDataUrl");
    expect(rustBackendSource).toContain("falling back to offscreen present-loop preview");
    expect(rustBackendSource).toContain("renderLoopPolicy");
    expect(rustBackendSource).toContain("indexCount");
    expect(rustBackendSource).toContain("instanceCount");
    expect(rustBackendSource).toContain("sceneObjectCount");
    expect(rustBackendSource).toContain("sceneGraphHash");
    expect(rustBackendSource).toContain("instanceBufferHash");
    expect(rustBackendSource).toContain("sceneMeshHash");
    expect(rustBackendSource).toContain("cameraUniformHash");
    expect(rustBackendSource).toContain("frameTargetPolicy");
    expect(rustBackendSource).toContain("frameTargetHash");
    expect(rustBackendSource).toContain("frameTargetAllocationCount");
    expect(nativeBridgeSource).toContain("Depth24Plus");
    expect(nativeBridgeSource).toContain("draw_indexed");
    expect(nativeBridgeSource).toContain("0..scene_pipeline.instance_count");
    expect(nativeBridgeSource).toContain("VertexStepMode::Instance");
    expect(nativeBridgeSource).toContain("banger_scene_instance_bytes");
    expect(nativeBridgeSource).toContain("banger_cube_vertex_bytes");
    expect(nativeBridgeSource).toContain("BangerNativeFrameTarget");
    expect(nativeBridgeSource).toContain("create_banger_frame_target");
    expect(nativeBridgeSource).toContain("persistent_resize_tracked_depth_target_v1");
    expect(nativeBridgeSource).toContain("forge.banger.maps_photorealistic_3d_tiles_contract.v1");
    expect(nativeBridgeSource).toContain("google_photorealistic_3d_tiles");
    expect(nativeBridgeSource).toContain("Cesium3DTileset_style_native_streamer");
    expect(nativeBridgeSource).toContain("CesiumGeoreference_style_floating_origin");
    expect(nativeBridgeSource).toContain("screen_space_error");
    expect(nativeBridgeSource).toContain("visible_on_screen");
  });

  it("paints Maps from Cesium Google tiles first and falls back to the Banger preview frame", () => {
    expect(canvasSurfacesSource).toContain("BangerSphereNativeViewport");
    expect(canvasSurfacesSource).toContain("getBangerPreviewFrame");
    expect(canvasSurfacesSource).toContain("getBangerGoogleTilesConfig");
    expect(canvasSurfacesSource).toContain("BangerMapsCesiumViewport");
    expect(canvasSurfacesSource).toContain("Cesium photorealistic tiles bootstrap");
    expect(canvasSurfacesSource).toContain("Cesium Google photorealistic 3D Tiles live");
    expect(canvasSurfacesSource).toContain("data-tileset-provider");
    expect(canvasSurfacesSource).toContain("data-tileset-renderer-model");
    expect(canvasSurfacesSource).toContain("data-tileset-georeference");
    expect(canvasSurfacesSource).toContain("data-tileset-lod");
    expect(canvasSurfacesSource).toContain("redactedTilesetEndpoint");
    expect(canvasSurfacesSource).toContain("previewFrameDataUrl");
    expect(canvasSurfacesSource).toContain("bangerSphereNativeFrame__preview");
    expect(canvasSurfacesSource).toContain("bangerSphereNativeFrame__fallback");
    expect(canvasSurfacesSource).toContain("target?.latitude");
    expect(canvasSurfacesSource).toContain("target?.longitude");
    expect(canvasSurfacesSource).toContain('aria-label={`${label} - ${status}`}');
    expect(canvasSurfacesSource).not.toContain('<span className="webExplorerNativeStatus">{label} - {status}</span>');
    expect(stylesSource).toContain(".bangerSphereNativeFrame__preview");
    expect(stylesSource).toContain(".bangerSphereNativeFrame");
    expect(stylesSource).toContain("pointer-events: none");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("width: var(--transcript-media-width)");
    expect(stylesSource).toContain("height: var(--transcript-media-flow-height)");
    expect(stylesSource).toContain("right: var(--transcript-media-right-gap)");
    expect(stylesSource).toContain("overflow: visible");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame");
    expect(stylesSource).toContain("inset: 50% auto auto 59%");
    expect(stylesSource).toContain("width: min(86.89173795355475vw, 107.86560573544727vh, 1139.0766445892043px)");
    expect(stylesSource).toContain("height: min(86.89173795355475vw, 107.86560573544727vh, 1139.0766445892043px)");
    expect(stylesSource).toContain("transform: translate3d(-50%, -50%, 0)");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__preview");
    expect(stylesSource).toContain("object-fit: contain");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__fallback");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .parallelCanvasClose");
    expect(stylesSource).toContain("display: none");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .webExplorerClose");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).toContain("width: min(100%, 1139.0766445892043px)");
    expect(appSource).toContain("canvasMapsClosing");
    expect(appSource).toContain("canvasPlanetsOpen || canvasMapsOpen || canvasMapsClosing");
    expect(appSource).toContain("closeCanvasMaps();");
    expect(appSource).toContain("mapsViewportTarget");
    expect(appSource).toContain("setMapsViewportTarget");
    expect(appSource).toContain("latitude: typeof event.latitude === \"number\" ? event.latitude : undefined");
    expect(appSource).toContain("mapsTarget={mapsViewportTarget}");
    expect(canvasSurfacesSource).toContain('mapsClosing ? "canvasSurfaces--mapsClosing" : ""');
    expect(stylesSource).toContain(".navIconButton--selected .shellIcon--nav-web");
    expect(stylesSource).toContain(".canvasSurfaces--mapsClosing .mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("animation: mapsSphereRailExit 260ms");
    expect(stylesSource).toContain("@keyframes mapsSphereRailExit");
    expect(stylesSource).toContain(".shell--maps-canvas-open .transcriptTextFrame");
    expect(stylesSource).toContain("var(--transcript-media-avoidance-width)");
    expect(stylesSource).toContain("object-fit: cover");
    expect(mainSource).toContain("provider: \"google_photorealistic_3d_tiles\"");
    expect(mainSource).toContain("rendererModel: \"cesium_for_unreal_style_3d_tileset\"");
    expect(mainSource).toContain("directRootTilesetEndpoint: \"https://tile.googleapis.com/v1/3dtiles/root.json\"");
    expect(mainSource).toContain("rootRequestTtlHours: 3");
    expect(mainSource).toContain("showCreditsOnScreen: true");
    expect(mainSource).toContain("policy: \"screen_space_error\"");
    expect(mainSource).toContain("authority: \"banger_tileset_residency_cache\"");
  });

  it("rebuilds stale Electron renderer assets before reusing the desktop fast path", () => {
    expect(launcherSource).toContain("preload.cjs");
    expect(launcherSource).toContain("if errorlevel 1 set NEED_ELECTRON_REBUILD=1");
    expect(launcherSource).toContain('if "%NEED_ELECTRON_REBUILD%"=="0" (');
    expect(launcherSource).toContain("Electron sources are newer");
  });
});
