import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const routerSource = readFileSync("src/renderer/HeaderSurfaceRouter.tsx", "utf8");
const appSource = readFileSync("src/renderer/App.tsx", "utf8");
const canvasSurfacesSource = readFileSync("src/renderer/CanvasSurfacesSlice.tsx", "utf8");
const stylesSource = readFileSync("src/renderer/styles.css", "utf8");
const launcherSource = readFileSync("run_ingen_electron_shell.cmd", "utf8");
const rustBackendSource = readFileSync("src/main/rust-backend.ts", "utf8");
const nativeBridgeSource = readFileSync("../ingen_native_services/src/bin/ingen_electron_backend_bridge.rs", "utf8");

describe("Banger native viewport contract", () => {
  it("keeps the Banger page as a full-screen native render surface with no inner frame prose", () => {
    expect(routerSource).toContain('"--surface-left": "0px"');
    expect(routerSource).toContain('"--surface-top": "0px"');
    expect(routerSource).toContain('"--surface-width": "100vw"');
    expect(routerSource).toContain('"--surface-height": "100vh"');
    expect(routerSource).toContain("getBangerPresentLoopBootstrap");
    expect(routerSource).toContain('sceneKind: "maps_sphere"');
    expect(routerSource).toContain("presentLoop.previewFrameDataUrl");
    expect(routerSource).toContain("rust_banger_wgpu_maps_sphere_present_loop_rgba8_to_bmp_data_url");
    expect(routerSource).toContain('"nativeViewportSlot nativeViewportSlot--live"');
    expect(routerSource).toContain("bangerSphereNativeFrame__fallback");
    expect(routerSource).toContain('data-native-contract={surface.nativeContract}');
    expect(routerSource).toContain('data-present-loop={presentLoop?.routeStatus ?? "pending"}');
    expect(routerSource).not.toContain("BangerPreviewFrameResult");
    expect(routerSource).not.toContain("native raster frame loading");
  });

  it("does not mount a browser WebGL globe inside the Banger surface", () => {
    expect(routerSource).not.toContain('from "cesium"');
    expect(routerSource).not.toContain('import("cesium")');
    expect(routerSource).not.toContain("new Cesium.Viewer");
    expect(routerSource).not.toContain("getBangerGoogleTilesConfig");
    expect(routerSource).not.toContain("bangerCesiumViewport");
    expect(stylesSource).not.toContain("bangerCesiumViewport");
    expect(stylesSource).not.toContain("cesium-widget");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot::after");
    expect(stylesSource).toContain("content: none");
    expect(stylesSource).toContain(".surface--banger .nativeViewportSlot--live");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallback");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).not.toContain("transparent 0 12%");
    expect(stylesSource).not.toContain("#1a9eb6 0 9%");
    expect(stylesSource).toContain("object-fit: cover");
  });

  it("launches the Rust native child-surface host instead of only probing offscreen", () => {
    expect(rustBackendSource).toContain("launchRustBangerNativeHost");
    expect(rustBackendSource).toContain("--banger-native-host");
    expect(rustBackendSource).toContain("FORGE_BANGER_PARENT_HWND");
    expect(rustBackendSource).toContain("shaderSourceHash");
    expect(rustBackendSource).toContain("renderPipelineHash");
    expect(rustBackendSource).toContain("bangerPreviewRgba8ToBmpDataUrl");
    expect(rustBackendSource).toContain("falling back to offscreen present-loop preview");
    expect(rustBackendSource).toContain("renderLoopPolicy");
    expect(rustBackendSource).toContain("indexCount");
    expect(rustBackendSource).toContain("instanceCount");
    expect(rustBackendSource).toContain("sceneObjectCount");
    expect(rustBackendSource).toContain("sceneGraphHash");
    expect(rustBackendSource).toContain("instanceBufferHash");
    expect(rustBackendSource).toContain("sceneMeshHash");
    expect(rustBackendSource).toContain("cameraUniformHash");
    expect(rustBackendSource).toContain("frameTargetPolicy");
    expect(rustBackendSource).toContain("frameTargetHash");
    expect(rustBackendSource).toContain("frameTargetAllocationCount");
    expect(nativeBridgeSource).toContain("Depth24Plus");
    expect(nativeBridgeSource).toContain("draw_indexed");
    expect(nativeBridgeSource).toContain("0..scene_pipeline.instance_count");
    expect(nativeBridgeSource).toContain("VertexStepMode::Instance");
    expect(nativeBridgeSource).toContain("banger_scene_instance_bytes");
    expect(nativeBridgeSource).toContain("banger_cube_vertex_bytes");
    expect(nativeBridgeSource).toContain("BangerNativeFrameTarget");
    expect(nativeBridgeSource).toContain("create_banger_frame_target");
    expect(nativeBridgeSource).toContain("persistent_resize_tracked_depth_target_v1");
  });

  it("paints the Maps sphere from the Banger preview frame returned by IPC", () => {
    expect(canvasSurfacesSource).toContain("BangerSphereNativeViewport");
    expect(canvasSurfacesSource).toContain("getBangerPreviewFrame");
    expect(canvasSurfacesSource).toContain("previewFrameDataUrl");
    expect(canvasSurfacesSource).toContain("bangerSphereNativeFrame__preview");
    expect(canvasSurfacesSource).toContain("bangerSphereNativeFrame__fallback");
    expect(canvasSurfacesSource).toContain('aria-label={`${label} - ${status}`}');
    expect(canvasSurfacesSource).not.toContain('<span className="webExplorerNativeStatus">{label} - {status}</span>');
    expect(stylesSource).toContain(".bangerSphereNativeFrame__preview");
    expect(stylesSource).toContain(".bangerSphereNativeFrame");
    expect(stylesSource).toContain("pointer-events: none");
    expect(stylesSource).toContain(".bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("width: var(--transcript-media-width)");
    expect(stylesSource).toContain("height: var(--transcript-media-flow-height)");
    expect(stylesSource).toContain("right: var(--transcript-media-right-gap)");
    expect(stylesSource).toContain("overflow: visible");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame");
    expect(stylesSource).toContain("width: min(58vw, 72vh, 760px)");
    expect(stylesSource).toContain("height: min(58vw, 72vh, 760px)");
    expect(stylesSource).toContain("transform: translate3d(-50%, -50%, 0)");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__preview");
    expect(stylesSource).toContain("object-fit: contain");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__fallback");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .parallelCanvasClose");
    expect(stylesSource).toContain("display: none");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .bangerSphereNativeFrame__fallbackSphere");
    expect(stylesSource).toContain("width: min(100%, 760px)");
    expect(appSource).toContain("canvasMapsClosing");
    expect(appSource).toContain("canvasPlanetsOpen || canvasMapsOpen || canvasMapsClosing");
    expect(appSource).toContain("closeCanvasMaps();");
    expect(canvasSurfacesSource).toContain('mapsClosing ? "canvasSurfaces--mapsClosing" : ""');
    expect(stylesSource).toContain(".navIconButton--selected .shellIcon--nav-web");
    expect(stylesSource).toContain(".canvasSurfaces--mapsClosing .mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("animation: mapsSphereRailExit 260ms");
    expect(stylesSource).toContain("@keyframes mapsSphereRailExit");
    expect(stylesSource).toContain(".shell--maps-canvas-open .transcriptTextFrame");
    expect(stylesSource).toContain("var(--transcript-media-avoidance-width)");
    expect(stylesSource).toContain("object-fit: cover");
  });

  it("rebuilds stale Electron renderer assets before reusing the desktop fast path", () => {
    expect(launcherSource).toContain("preload.cjs");
    expect(launcherSource).toContain("ingen-electron-launch-build-%WORKSPACE_BUILD_ID%.lock");
    expect(launcherSource).toContain("set DESKTOP_AUTO_REBUILD=1");
    expect(launcherSource).toContain("FORGE_ELECTRON_DESKTOP_STABLE");
    expect(launcherSource).toContain("if errorlevel 1 set NEED_ELECTRON_REBUILD=1");
    expect(launcherSource).toContain('if "%NEED_ELECTRON_REBUILD%"=="0" (');
    expect(launcherSource).toContain("Electron sources are newer");
    expect(launcherSource).toContain("set RESTART_RUNNING_APP_AFTER_REBUILD=1");
    expect(launcherSource).toContain("Restarting existing InGen Electron process so the fresh renderer bundle is visible");
    expect(launcherSource).toContain("Stop-Process -Id $_.ProcessId -Force");
  });
});
