import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const mainSource = readFileSync(join(process.cwd(), "src", "main", "main.ts"), "utf8");
const appSource = readFileSync(join(process.cwd(), "src", "renderer", "App.tsx"), "utf8");
const brainCanvasSource = readFileSync(join(process.cwd(), "src", "renderer", "BrainCanvas.tsx"), "utf8");
const canvasSource = readFileSync(join(process.cwd(), "src", "renderer", "CanvasSurfacesSlice.tsx"), "utf8");
const composerBurstSource = readFileSync(join(process.cwd(), "src", "renderer", "ComposerSendBurst.tsx"), "utf8");
const rendererSource = readFileSync(join(process.cwd(), "src", "renderer", "PanelsChatBottomSlice.tsx"), "utf8");
const moduleLogosSource = readFileSync(join(process.cwd(), "src", "renderer", "module-logos.tsx"), "utf8");
const storeSource = readFileSync(join(process.cwd(), "src", "renderer", "panels-chat-bottom-store.ts"), "utf8");
const sidebarSource = readFileSync(join(process.cwd(), "src", "renderer", "SidebarSlice.tsx"), "utf8");
const stylesSource = readFileSync(join(process.cwd(), "src", "renderer", "styles.css"), "utf8");
const preloadCjsSource = readFileSync(join(process.cwd(), "preload.cjs"), "utf8");
const brainSource = readFileSync(join(process.cwd(), "..", "..", "src", "brain.rs"), "utf8");
const contractSource = readFileSync(join(process.cwd(), "contract", "src", "main.rs"), "utf8");

describe("LLM multimodal attachments", () => {
  it("normalizes local uploads into provider-native multimodal content", () => {
    expect(mainSource).toContain("openAiResponseContent");
    expect(mainSource).toContain('type: "input_image"');
    expect(mainSource).toContain('type: "input_file"');
    expect(mainSource).toContain("file_data: attachment.openAiFileDataUrl");
    expect(mainSource).toContain("const text = userTextWithAttachmentContext(userText, attachments)");
    expect(mainSource).toContain("attachments.flatMap((attachment) => attachment.visualSnapshots)");
    expect(mainSource).toContain('type: "image_url"');
    expect(mainSource).toContain("image_url: { url: snapshot.imageUrl }");
  });

  it("creates visual snapshots for images, videos, and 3D files", () => {
    expect(mainSource).toContain("captureImageSnapshot");
    expect(mainSource).toContain("analyzeVideoAttachment");
    expect(mainSource).toContain("model3dSummaryForFile");
    expect(mainSource).toContain('source: "image" | "video-frame" | "model3d-summary"');
    expect(mainSource).toContain("video frame extraction unavailable");
    expect(mainSource).toContain("3D model summary");
  });

  it("sends rich video metadata, multiple frames, and extracted subtitle cues to the LLM", () => {
    expect(mainSource).toContain("PANELS_CHAT_BOTTOM_MAX_VISUAL_SNAPSHOTS = 6");
    expect(mainSource).toContain("ProviderVideoMetadata");
    expect(mainSource).toContain("videoMetadataText");
    expect(mainSource).toContain("quality_label=");
    expect(mainSource).toContain("resolution=");
    expect(mainSource).toContain("duration=");
    expect(mainSource).toContain("snapshot_times=");
    expect(mainSource).toContain("video.textTracks");
    expect(mainSource).toContain("track.cues || track.activeCues");
    expect(mainSource).toContain("subtitles_extracted=");
  });

  it("extracts useful text from code and written documents", () => {
    expect(mainSource).toContain('".rs"');
    expect(mainSource).toContain('".py"');
    expect(mainSource).toContain('".docx"');
    expect(mainSource).toContain('".pptx"');
    expect(mainSource).toContain("officeTextPreviewForFile");
    expect(mainSource).toContain("xmlTextNodes");
    expect(mainSource).toContain("PANELS_CHAT_BOTTOM_MAX_TEXT_PREVIEW_BYTES");
  });

  it("carries recent session attachments into follow-up LLM turns", () => {
    expect(mainSource).toContain("const pendingUploadItems = composerUploadItemsForCommand(command)");
    expect(mainSource).toContain("composerUploadItemsForCommand(command)");
    expect(mainSource).toContain("function providerUploadItemsForCommand");
    expect(mainSource).toContain("message.attachments ?? []");
    expect(mainSource).toContain("composerUploadPreviewItems.get(preview.id)");
    expect(mainSource).toContain("const providerUploadItems = providerUploadItemsForCommand(pendingUploadItems)");
    expect(mainSource).toContain("providerAttachments = await providerAttachmentsFromUploads(providerUploadItems)");
    expect(mainSource).toContain("const currentAttachmentIds = new Set(pendingUploadItems.map((item) => item.id))");
    expect(mainSource).toContain("attachments: attachmentPreviews");
    expect(mainSource).toContain("requestTranscriptWithUser");
    expect(mainSource).toContain("liveTextSink");
    expect(mainSource).toContain("providerAttachmentCache");
  });

  it("carries conversation memory and previous user intent into attachment-only provider turns", () => {
    expect(mainSource).toContain("function recentConversationWindow");
    expect(mainSource).toContain("PANELS_CHAT_BOTTOM_CONTEXT_TOKEN_BUDGET");
    expect(mainSource).toContain("PANELS_CHAT_BOTTOM_COMPACT_AT_TOKENS");
    expect(mainSource).toContain("PANELS_CHAT_BOTTOM_RECENT_CONTEXT_TOKENS");
    expect(mainSource).toContain("function conversationMemoryContext");
    expect(mainSource).toContain("function conversationContextPlan");
    expect(mainSource).toContain("CONTEXT_COMPACTION_EVENT_COMMAND");
    expect(mainSource).toContain("function contextCompactionEventMessage");
    expect(mainSource).toContain("contextCompactionEventMessage(\"compressing\"");
    expect(mainSource).toContain("contextCompactionEventMessage(\"compressed\"");
    expect(mainSource).toContain("context_compaction_started");
    expect(mainSource).toContain("context_compaction_completed");
    expect(mainSource).toContain("!message.id.startsWith(\"assistant-status-\")");
    expect(mainSource).toContain("function estimatedPromptTokens");
    expect(mainSource).toContain("BRAIN_REINJECTED_AFTER_COMPACTION");
    expect(mainSource).toContain("brainBootManifest()");
    expect(mainSource).toContain("Memoire compacte de la conversation anterieure:");
    expect(mainSource).toContain("PANELS_CHAT_BOTTOM_DOCUMENT_MEMORY_BYTES");
    expect(mainSource).toContain("function sessionDocumentMemoryContext");
    expect(mainSource).toContain("Registre des documents de la session:");
    expect(mainSource).toContain("created_or_returned_by_assistant=true");
    expect(mainSource).toContain("provided_by_user=true");
    expect(mainSource).toContain("function previousUserIntentForAttachmentTurn");
    expect(mainSource).toContain("function providerUserTextForTurn");
    expect(mainSource).toContain("TACHE ACTIVE OBLIGATOIRE:");
    expect(mainSource).toContain("Ne demande pas ce que l'utilisateur veut faire avec l'image ou le document.");
    expect(mainSource).toContain("L'utilisateur vient d'envoyer les pieces jointes pour repondre a sa demande precedente.");
    expect(mainSource).toContain("openAiResponseConversationInput(userText, attachments, userMessageId, transcript)");
    expect(mainSource).toContain("input: await openAiResponseConversationInput(userText, attachments, userMessageId, transcript)");
    expect(mainSource).toContain("Conversation recente:");
    expect(mainSource).toContain("const providerUserText = providerUserTextForTurn(userText, attachments, userMessageId, transcript)");
    expect(mainSource).toContain("function appendTranscriptMessageForActiveSession");
    expect(mainSource).toContain("const requestSessionId = activeSession.sessionId");
    expect(mainSource).toContain("const requestTranscriptBeforeSend = [...panelsChatBottomState.transcript]");
    expect(mainSource).toContain("requestTranscriptWithUser");
    expect(mainSource).toContain("liveAssistantMessageId");
  });

  it("opens uploaded and assistant-created files from other sessions in a dedicated Files tab", () => {
    expect(mainSource).toContain("function sessionFilesSnapshot");
    expect(mainSource).toContain('ipcMain.handle("forge:get-session-files-snapshot"');
    expect(mainSource).toContain("filesFromArchiveSession(session)");
    expect(mainSource).toContain("rememberArchiveAttachmentPreview(attachment)");
    expect(mainSource).toContain("filesFromTranscript(lane.transcript)");
    expect(preloadCjsSource).toContain("getSessionFilesSnapshot");
    expect(canvasSource).toContain("openSessionFiles");
    expect(canvasSource).toContain("if (sessionFilesOpen) {\n      return;\n    }");
    expect(canvasSource).toContain("SessionFilesMenuBody");
    expect(canvasSource).toContain("Files from Another Session");
    expect(canvasSource).toContain("chooseSessionFilesGroup");
    expect(canvasSource).toContain("setSelectedSessionFilesGroup(group)");
    expect(canvasSource).toContain("setSessionFilesTabActive(true)");
    expect(canvasSource).toContain("canvasPaneTabs__tab--sessionFiles");
    expect(canvasSource).toContain("canvasSessionFilesChoice");
    expect(canvasSource).toContain("canvasSessionFilesChoice__previews");
    expect(canvasSource).toContain("group.files.slice(0, 4).map");
    expect(canvasSource).toContain("<CanvasFilePreview file={file} compact activeMotionPreview />");
    expect(canvasSource).toContain("ThreeUploadPreview");
    expect(canvasSource).toContain("activeMotionPreview = false");
    expect(canvasSource).toContain("autoPlay={activeMotionPreview}");
    expect(canvasSource).toContain("loop={activeMotionPreview}");
    expect(canvasSource).toContain('preload={activeMotionPreview ? "auto" : "metadata"}');
    expect(canvasSource).toContain('file.kind === "model3d" && activeMotionPreview');
    expect(canvasSource).toContain("canvasFileTile__model--sessionChoice");
    expect(canvasSource).toContain("function CanvasFileFallbackPreview");
    expect(canvasSource).toContain("onError={() => setFailed(true)}");
    expect(canvasSource).toContain("setMenuOpen(false)");
    expect(canvasSource).toContain("style={{ \"--canvas-file-enter-delay\"");
    expect(stylesSource).toContain(".canvasPaneTabs__menu--sessionFilesExpanded");
    expect(stylesSource).toContain(".canvasSessionFilesChoice");
    expect(stylesSource).toContain(".canvasSessionFilesChoice__preview .canvasFileTile__media");
    expect(stylesSource).toContain(".canvasFileTile__visualFallback");
    expect(stylesSource).toContain(".canvasPaneTabs__menu--sessionFilesExpanded::-webkit-scrollbar-button");
    expect(stylesSource).toContain("scrollbar-width: thin");
    expect(stylesSource).toContain("scrollbar-color: color-mix(in oklab, var(--forge-line), #000 22%) transparent");
    expect(stylesSource).toContain("width: 3px");
    expect(stylesSource).toContain("height: min(560px, calc(100vh - 210px))");
    expect(stylesSource).toContain("grid-auto-rows: minmax(132px, 1fr)");
    expect(stylesSource).toContain("min-height: calc(100% - 31px)");
    expect(stylesSource).toContain("grid-template-rows: minmax(0, 1fr)");
    expect(stylesSource).toContain("min-height: clamp(128px, 22vh, 180px)");
    expect(stylesSource).toContain(".canvasSessionFilesChoice__meta");
    expect(stylesSource).toContain("min-height: 24px");
    expect(stylesSource).toContain(".canvasPaneTabs__menu .canvasSessionFilesChoice::before");
    expect(stylesSource).toContain("transform: translateY(-1px) scale(1.012)");
    expect(stylesSource).toContain(".canvasSessionFilesChoice__preview .canvasFileTile__model--sessionChoice");
    expect(stylesSource).toContain(".canvasSessionFilesChoice:hover .canvasSessionFilesChoice__previews");
    expect(stylesSource).toContain(".canvasPaneTabs__tab--sessionFiles");
    expect(stylesSource).toContain("@keyframes canvasFileTileEnter");
  });

  it("executes /searcharchive_ locally as a Brain archive command", () => {
    expect(mainSource).toContain("parseSearchArchiveCodeAct(draft)");
    expect(mainSource).toContain("localSearchArchiveStatus(searchArchiveRequest)");
    expect(mainSource).toContain("forge:search-archive");
    expect(mainSource).toContain("archiveTranscriptMessage(activeSession, assistantMessage)");
  });

  it("boots every LLM session with Brain access before provider execution", () => {
    expect(mainSource).toContain("BRAIN_BOOT_MANIFEST v1");
    expect(mainSource).toContain("BRAIN_IDENTITY_MEMORY v1");
    expect(mainSource).toContain('return join(app.getPath("userData"), "brain", "identity-memory.json")');
    expect(mainSource).toContain("restoreBrainIdentityContextFromDisk()");
    expect(mainSource).toContain("persistBrainIdentityContext()");
    expect(mainSource).toContain('if (!user && !assistant && !homeLocation) return "";');
    expect(mainSource).toContain("user_home_location=${JSON.stringify(homeLocation)}");
    expect(mainSource).toContain("Never treat user_home_location as live device geolocation or as the default /maps_ target.");
    expect(mainSource).not.toContain("si_demande_nom_ou_prenom");
    expect(mainSource).not.toContain("source=Brain Memory > Identity editor; these fields are durable user-confirmed Brain memory.");
    expect(mainSource).not.toContain("When the user asks your name, what you are called, comment tu t'appelles");
    expect(mainSource).toContain("brainIdentityMemoryManifest()");
    expect(mainSource).toContain("updateBrainIdentityContext(command);\n  const parallelSessionIndex");
    expect(mainSource).toContain("updateBrainIdentityContext(command);\n  const lane = ensureParallelChatLane");
    expect(storeSource).toContain('import { readBrainAgentMemory, readBrainUserLocationMemory, readBrainUserMemory } from "./brain-user-memory-store";');
    expect(storeSource).toContain('if (command.kind === "send_chat" || command.kind === "send_parallel_chat_batch")');
    expect(storeSource).toContain("userFirstName: userMemory.preferredFirstName");
    expect(storeSource).toContain("agentFirstName: agentMemory.preferredFirstName");
    expect(storeSource).toContain("userHomeLocation: locationMemory.homeLocation");
    expect(mainSource).toContain("const generalBrainCodeActCommands = BRAIN_CODEACT_COMMANDS.filter");
    expect(mainSource).not.toContain("command !== BRAIN_QUESTIONNAIRE_COMMAND");
    expect(mainSource).not.toContain("item.command !== BRAIN_QUESTIONNAIRE_COMMAND");
    expect(mainSource).toContain("codeact_descriptions=${commandDescriptions}");
    expect(mainSource).toContain("codeact_commands=${generalBrainCodeActCommands.join");
    expect(mainSource).toContain("ensureBrainBootTranscript");
    expect(mainSource).toContain("brainBootManifest()");
    expect(brainCanvasSource).toContain("const commitUserMemory = (value: string)");
    expect(brainCanvasSource).toContain("const commitAgentMemory = (value: string)");
    expect(brainCanvasSource).toContain("const commitLocationMemory = (value: string)");
    expect(brainCanvasSource).toContain("function BrainMemoryLocationField");
    expect(brainCanvasSource).toContain("role=\"combobox\"");
    expect(brainCanvasSource).toContain('label="Home city"');
    expect(brainCanvasSource).not.toContain("Lieu de vie");
    expect(brainCanvasSource).toContain("searchCitySuggestions");
    expect(brainCanvasSource).toContain("fallbackPhotonCitySuggestionLabels");
    expect(brainCanvasSource).not.toContain("HOME_LOCATION_SUGGESTIONS");
    expect(brainCanvasSource).not.toContain("Paris, France");
    expect(brainCanvasSource).not.toContain("City lookup unavailable");
    expect(preloadCjsSource).toContain("forge:search-city-suggestions");
    expect(mainSource).toContain("https://places.googleapis.com/v1/places:autocomplete");
    expect(mainSource).toContain('includedPrimaryTypes: ["(cities)"]');
    expect(mainSource).toContain("GOOGLE_PLACES_API_KEY");
    expect(mainSource).toContain("https://photon.komoot.io/api/");
    expect(mainSource).toContain('url.searchParams.append("layer", "city")');
    expect(mainSource).toContain('url.searchParams.append("layer", "locality")');
  });

  it("continues automatically after a Brain segment CodeAct is activated", () => {
    expect(mainSource).toContain("function brainSegmentFromAssistantText");
    expect(mainSource).toContain("function activeBrainSegmentFromTranscript");
    expect(mainSource).toContain("function suppressRepeatedBrainSegmentCodeAct");
    expect(mainSource).toContain("function removeBrainSegmentCommandLines");
    expect(mainSource).toContain("function brainSegmentContinuationUserText");
    expect(mainSource).toContain("function executeAssistantModuleCodeActs");
    expect(mainSource).toContain("active=science");
    expect(mainSource).toContain("active=coding");
    expect(mainSource).toContain("do not emit ${BRAIN_SCIENCE_COMMAND} again");
    expect(mainSource).toContain("do not emit ${BRAIN_CODING_COMMAND} again");
    expect(mainSource).toContain("panelsChatBottomState.activeBrainSegment = activeBrainSegmentFromTranscript(panelsChatBottomState.transcript)");
    expect(mainSource).toContain("assistantMessage = suppressRepeatedBrainSegmentCodeAct(assistantMessage, panelsChatBottomState.activeBrainSegment)");
    expect(mainSource).toContain("const activatedBrainSegment = brainSegmentFromAssistantText(assistantMessage.text)");
    expect(mainSource).toContain("activatedBrainSegment !== previousBrainSegment");
    expect(mainSource).toContain("continuationMessage = suppressRepeatedBrainSegmentCodeAct(continuationMessage, panelsChatBottomState.activeBrainSegment)");
    expect(mainSource).toContain("suppressedRepeatedBrainSegment");
    expect(mainSource).toContain("const continuationUserText = brainSegmentContinuationUserText(draft, activatedBrainSegment)");
    expect(mainSource).toContain("Le catalogue ${catalog} est maintenant injecte");
    expect(mainSource).toContain("Loop stream mode");
    expect(mainSource).toContain("activate ${BRAIN_QUESTIONNAIRE_COMMAND}");
    expect(mainSource).toContain("q1_options/q2_options/q3_options/q4_options/q5_options");
    expect(mainSource).toContain("three contextual expert option cards");
    expect(mainSource).toContain('Each option must follow "Label (Tag) - 1-2 useful French sentences: benefit, tradeoff, when to choose it"');
    expect(mainSource).toContain("Recommended, Fast, Quality, Ambitious, Cheaper, Safer or Riskier");
    expect(mainSource).toContain("color:#38bdf8");
    expect(mainSource).toContain("colors:#38bdf8,#a855f7");
    expect(mainSource).toContain("never include arbitrary CSS or JS");
    expect(mainSource).toContain('mark "(Recommended)"');
    expect(mainSource).toContain("Forbidden: Option 1/2/3");
    expect(mainSource).toContain("comparer plusieurs pistes");
    expect(mainSource).toContain("ne reactive pas ${command}");
    expect(mainSource).toContain("function enforceQuestionnaireLoopPause");
    expect(mainSource).toContain("assistantMessage = enforceQuestionnaireLoopPause(assistantMessage)");
    expect(mainSource).toContain("continuationMessage = enforceQuestionnaireLoopPause(continuationMessage)");
    expect(mainSource).toContain("session.working = transcriptHasOpenQuestionnaire(latestCommittedTranscript)");
    expect(mainSource).toContain("transcriptHasOpenQuestionnaire(panelsChatBottomState.transcript)");
  });

  it("registers the English questionnaire CodeAct and renders it above the composer", () => {
    expect(brainSource).toContain('pub const BRAIN_QUESTIONNAIRE_COMMAND: &str = "/questionnaire_"');
    expect(brainSource).toContain("brain_questionnaire_codeact_template()");
    expect(brainSource).toContain("Use /questionnaire_ from General, Science or Coding Brain");
    expect(brainSource).toContain("brain_questionnaire_codeact_template()");
    expect(brainSource).toContain("brain_questionnaire_codeact_template(),");
    expect(brainSource).toContain("BRAIN_SCIENCE_VISIBLE_CATALOG.contains(BRAIN_QUESTIONNAIRE_COMMAND)");
    expect(brainSource).toContain("BRAIN_CODING_VISIBLE_CATALOG.contains(BRAIN_QUESTIONNAIRE_COMMAND)");
    expect(brainSource).toContain("when key scientific, engineering, constraint, scope, risk or success-criteria choices are missing");
    expect(brainSource).toContain("when key product, scope, file, risk, style, stack or success-criteria choices are missing");
    expect(brainSource).toContain("q1_options");
    expect(brainSource).toContain("host adds Other");
    expect(brainSource).toContain("No Option 1/2/3, vague answers or Other");
    expect(brainSource).toContain("three concrete expert options");
    expect(brainSource).toContain("benefit, tradeoff, when to choose");
    expect(brainSource).toContain("Max 5 questions");
    expect(brainSource).toContain("Skip trivial tasks or obvious safe defaults");
    expect(brainSource).toContain("colors:#hex,#hex");
    expect(brainSource).toContain("paginated_options");
    expect(contractSource).toContain("BRAIN_QUESTIONNAIRE_COMMAND,\\n\\");
    expect(rendererSource).toContain('[BRAIN_QUESTIONNAIRE_COMMAND, "Questionnaire opened"]');
    expect(rendererSource).toContain("function parseQuestionnaireFromMessage");
    expect(rendererSource).toContain("function ComposerQuestionnaire");
    expect(rendererSource).toContain("function parseQuestionnaireAnswerTable");
    expect(rendererSource).toContain("function QuestionnaireAnswerTable");
    expect(rendererSource).toContain("questionnaireAnswerRows.length > 0");
    expect(rendererSource).toContain("const promptId = useId()");
    expect(rendererSource).toContain("function questionnaireOptionCopy");
    expect(rendererSource).toContain("const QUESTIONNAIRE_TAGS");
    expect(rendererSource).toContain("function questionnaireOptionTags");
    expect(rendererSource).toContain("function supportsQuestionnaireColor");
    expect(rendererSource).toContain("function extractQuestionnaireColors");
    expect(rendererSource).toContain("function questionnaireColorPreviewStyle");
    expect(rendererSource).toContain("CSS.supports(\"color\", candidate)");
    expect(rendererSource).toContain("function questionnaireOptionsFor");
    expect(rendererSource).toContain("function parsedQuestionnaireQuestion");
    expect(rendererSource).toContain("function splitQuestionnaireOptions(value: string, allowComma = false)");
    expect(rendererSource).toContain("const separator = allowComma");
    expect(rendererSource).toContain("\\s*\\|\\s*");
    expect(rendererSource).toContain('title: slots.get("title")?.trim() || ""');
    expect(rendererSource).toContain("const questionnaireTitle = questionnaire.title.trim()");
    expect(rendererSource).toContain('questionnaireTitle ? "composerQuestionnaire--titled" : "composerQuestionnaire--untitled"');
    expect(rendererSource).toContain("composerQuestionnaire__headerSpacer");
    expect(rendererSource).toContain("questions.slice(0, 5)");
    expect(rendererSource).toContain("Base \\u00e9quilibr\\u00e9e (Recommended)");
    expect(rendererSource).toContain("Version qualit\\u00e9 sup\\u00e9rieure");
    expect(rendererSource).toContain("currentAnswerComplete");
    expect(rendererSource).toContain("window.setTimeout(() => goToPage(pageIndex + 1)");
    expect(rendererSource).toContain("disabled={!currentAnswerComplete || isClosing}");
    expect(rendererSource).toContain("setLeavingPageIndex(pageIndex)");
    expect(rendererSource).toContain("setPageMotionDirection(clampedNextPageIndex > pageIndex ? \"forward\" : \"back\")");
    expect(rendererSource).toContain("commitAnswersWith(nextAnswers)");
    expect(rendererSource).toContain("setIsClosing(true)");
    expect(rendererSource).toContain("composerQuestionnaire--closing");
    expect(rendererSource).toContain("composerQuestionnaire__pageStage");
    expect(rendererSource).toContain("`composerQuestionnaire__page--${motionState}`");
    expect(rendererSource).toContain('value="Autre"');
    expect(rendererSource).toContain("Prototype rapide");
    expect(rendererSource).toContain("composerQuestionnaire__promptQuestion");
    expect(rendererSource).toContain("composerQuestionnaire__promptHint");
    expect(rendererSource).toContain('placeholder={"Pr\\u00e9cise ta r\\u00e9ponse..."}');
    expect(rendererSource).toContain('value={candidateAnswer?.kind === "other" ? candidateAnswer.otherText : ""}');
    expect(rendererSource).toContain("onClick={(event) => event.stopPropagation()}");
    expect(rendererSource).toContain("questionnaireFocusScrim");
    expect(rendererSource).toContain("composerQuestionnaire__optionIndex");
    expect(rendererSource).toContain("{optionIndex + 1}");
    expect(rendererSource).toContain("composerQuestionnaire__optionCopy");
    expect(rendererSource).toContain("composerQuestionnaire__optionLabel");
    expect(rendererSource).toContain("optionCopy.tags.map");
    expect(rendererSource).toContain("optionCopy.colors.length > 0 ? \"composerQuestionnaire__option--colorPreview\" : \"\"");
    expect(rendererSource).toContain("style={questionnaireColorPreviewStyle(optionCopy.colors)}");
    expect(rendererSource).toContain('aria-label="Question suivante"');
    expect(rendererSource).toContain("composerQuestionnaire__arrow--primary");
    expect(rendererSource).toContain("commitQuestionnaireAnswers");
    expect(rendererSource).toContain('kind: "send_chat"');
    expect(rendererSource).toContain('if (messages[index].role === "user")');
    expect(rendererSource).toContain("event.command === BRAIN_QUESTIONNAIRE_COMMAND");
    expect(rendererSource).toContain("latestQuestionnaireFromMessages(canvasMessages)");
    expect(rendererSource).toContain('composerQuestionnaire ? "panelsChatBottom--questionnaireOpen" : ""');
    expect(rendererSource).toContain('permissionMode === "self-directed" ? "permissionModeTrigger--selfDirected" : ""');
    expect(stylesSource).toContain(".composerQuestionnaire");
    expect(stylesSource).toContain(".questionnaireAnswerTable");
    expect(stylesSource).toContain(".questionnaireAnswerTable__row");
    expect(stylesSource).toContain(".questionnaireAnswerTable__answer");
    expect(stylesSource).toContain("--questionnaire-width: min(756px, calc(var(--chat-width) - 8px))");
    expect(stylesSource).toContain(".panelsChatBottom--questionnaireOpen");
    expect(stylesSource).toContain("z-index: 31");
    expect(stylesSource).toContain("bottom: calc(var(--composer-bottom) + var(--composer-live-height, 82px))");
    expect(stylesSource).toContain("height: min(334px, calc(100vh - var(--composer-bottom) - var(--composer-live-height, 82px) - 86px))");
    expect(stylesSource).toContain("padding: 8px 6px 5px");
    expect(stylesSource).toContain("background: var(--forge-sidebar-bg)");
    expect(stylesSource).toContain("overflow: hidden");
    expect(stylesSource).toContain(".questionnaireFocusScrim");
    expect(stylesSource).toContain("backdrop-filter: blur(2px) saturate(0.82)");
    expect(stylesSource).toContain(".composerQuestionnaire--closing");
    expect(stylesSource).toContain("animation: composerQuestionnaireExit 320ms cubic-bezier(0.2, 0.85, 0.24, 1) both");
    expect(stylesSource).toContain(".composerQuestionnaire__pageStage");
    expect(stylesSource).toContain(".composerQuestionnaire__page--active.composerQuestionnaire__page--forward");
    expect(stylesSource).toContain("animation: questionnairePageInFromRight 260ms cubic-bezier(0.16, 1, 0.3, 1) both");
    expect(stylesSource).toContain(".composerQuestionnaire__page--leaving.composerQuestionnaire__page--forward");
    expect(stylesSource).toContain("animation: questionnairePageOutToLeft 260ms cubic-bezier(0.5, 0, 0.2, 1) both");
    expect(stylesSource).toContain(".composerQuestionnaire__options");
    expect(stylesSource).toContain("grid-template-columns: minmax(0, 1fr)");
    expect(stylesSource).toContain("grid-template-rows: repeat(4, minmax(0, 1fr))");
    expect(stylesSource).toContain(".shell .composerQuestionnaire__option:first-child");
    expect(stylesSource).toContain("border-radius: 6px 6px 0 0 !important");
    expect(stylesSource).toContain(".shell .composerQuestionnaire__option:nth-child(2)");
    expect(stylesSource).toContain(".shell .composerQuestionnaire__option:nth-child(3)");
    expect(stylesSource).toContain("border-radius: 0 !important");
    expect(stylesSource).toContain(".shell .composerQuestionnaire__option:last-child");
    expect(stylesSource).toContain("border-radius: 0 0 6px 6px !important");
    expect(stylesSource).toContain(".composerQuestionnaire__optionIndex");
    expect(stylesSource).toContain("height: auto");
    expect(stylesSource).toContain(".composerQuestionnaire__option::after");
    expect(stylesSource).toContain(".composerQuestionnaire__option--colorPreview::before");
    expect(stylesSource).toContain("var(--questionnaire-option-color-a)");
    expect(stylesSource).toContain("filter: blur(28px) saturate(1.2)");
    expect(stylesSource).toContain("-webkit-mask-composite: xor");
    expect(stylesSource).toContain("mask-composite: exclude");
    expect(stylesSource).toContain(".composerQuestionnaire__optionCopy");
    expect(stylesSource).toContain(".composerQuestionnaire__optionLabel em");
    expect(stylesSource).toContain("linear-gradient(var(--forge-sidebar-bg), var(--forge-sidebar-bg)) padding-box");
    expect(stylesSource).toContain("color-mix(in oklab, var(--forge-sidebar-bg), transparent 28%)");
    expect(stylesSource).toContain("linear-gradient(90deg, #67e8f9, #34d399) border-box");
    expect(stylesSource).toContain(".composerQuestionnaire__option:hover .composerQuestionnaire__optionLabel");
    expect(stylesSource).toContain("color: currentColor");
    expect(stylesSource).toContain("border-color: color-mix(in oklab, #67e8f9, #34d399 42%)");
    expect(stylesSource).toContain("box-shadow: inset 0 0 0 1px color-mix(in oklab, #67e8f9, #34d399 42%, transparent 58%)");
    expect(stylesSource).toContain(".composerQuestionnaire__prompt");
    expect(stylesSource).toContain("gap: 10px");
    expect(stylesSource).toContain("padding: 0");
    expect(stylesSource).toContain(".composerQuestionnaire--untitled .composerQuestionnaire__header");
    expect(stylesSource).toContain("padding-top: 0");
    expect(stylesSource).toContain("padding-right: 104px");
    expect(stylesSource).toContain(".composerQuestionnaire__promptQuestion");
    expect(stylesSource).toContain(".composerQuestionnaire__promptHint");
    expect(stylesSource).toContain("white-space: normal");
    expect(stylesSource).toContain("opacity: 0;");
    expect(stylesSource).toContain(".composerQuestionnaire__otherInput");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain("border: 0");
    expect(stylesSource).toContain(".composerQuestionnaire__option:has(textarea:focus)");
    expect(stylesSource).toContain("outline: 0");
    expect(stylesSource).toContain(".permissionModeTrigger--selfDirected > span");
    expect(stylesSource).toContain(".permissionModeTrigger--selfDirected > svg:first-child");
    expect(stylesSource).toContain("animation: permissionSelfDirectedTextFlow 18s ease-in-out infinite");
    expect(stylesSource).toContain("animation: permissionSelfDirectedIconFlow 18s ease-in-out infinite");
  });

  it("lets Self-Directed visibly author bounded follow-up prompts in the composer", () => {
    expect(mainSource).toContain("SELF_DIRECTED_MODE v1");
    expect(mainSource).toContain("After the correct Brain is active");
    expect(mainSource).toContain("The final question must define the stop condition");
    expect(mainSource).toContain("SELF_DIRECTED_QUESTIONNAIRE_ANSWERS v1");
    expect(mainSource).toContain("SELF_DIRECTED_GOAL_REACHED");
    expect(rendererSource).toContain("SELF_DIRECTED_CONTINUATION v1");
    expect(rendererSource).toContain("SELF_DIRECTED_PROJECT_EXPANSION v1");
    expect(rendererSource).toContain("SELF_DIRECTED_LOOP_SAFETY_FUSE = 24");
    expect(rendererSource).toContain("role=agent_authored_prompt_visible_in_composer");
    expect(rendererSource).toContain("selfDirectedQuestionnaireAnswersPrompt(value)");
    expect(rendererSource).toContain("selfDirectedAssistantReachedGoal(lastAssistant.text)");
    expect(rendererSource).toContain("typeSelfDirectedDraft(selfDirectedContinuationPrompt");
    expect(rendererSource).toContain('selfDirectedDrafting ? "composer--selfDirectedDrafting" : ""');
    expect(rendererSource).toContain('permissionMode === "self-directed" ? "panelsChatBottom--selfDirected" : ""');
    expect(rendererSource).toContain('permissionMode === "self-directed" && targetParallelIndex === 0');
    expect(rendererSource).toContain("startSelfDirectedRun(value)");
    expect(rendererSource).toContain("research the web when current knowledge may be stale");
    expect(rendererSource).toContain("choose or switch Brain when useful");
    expect(stylesSource).toContain(".composer--selfDirectedDrafting::before");
    expect(stylesSource).toContain(".panelsChatBottom--selfDirected .composerQuestionnaire");
    expect(stylesSource).toContain(".panelsChatBottom--selfDirected .composerQuestionnaire__promptQuestion");
    expect(stylesSource).toContain("@keyframes composerSelfDirectedDraftFlow");
  });

  it("keeps in-flight CodeAct cycles visible when parallel sessions open", () => {
    const addParallelStart = appSource.indexOf("const addParallelCanvas");
    const addParallelEnd = appSource.indexOf("const removableParallelIndexes", addParallelStart);
    const addParallelSource = appSource.slice(addParallelStart, addParallelEnd);

    expect(addParallelSource).toContain('setParallelPrompts((prompts) => [...prompts, ""])');
    expect(addParallelSource).not.toContain("setCanvasWebExplorerOpen(false)");
    expect(rendererSource).not.toContain("activeQuestionnaire && !parallelMode");
    expect(rendererSource).toContain("const composerQuestionnaire = focusedParallelQuestionnaire");
    expect(rendererSource).toContain("parallelSessionIndex: parallelSessionIndex > 0 ? parallelSessionIndex : undefined");
    expect(rendererSource).toContain("latestQuestionnaireFromMessages(laneMessages)");
    expect(storeSource).toContain("optimisticSendSnapshot(state.snapshot, parallelSessionIndex, draft, attachments, internalPrompt, replaceAssistantMessageId)");
    expect(storeSource).toContain("withParallelLaneMessages(snapshot, parallelSessionIndex, nextTranscript)");
  });

  it("keeps Gmail CodeAct user-facing text normal and opens WebExplorer from results", () => {
    expect(mainSource).toContain("ecris ta propre phrase naturelle");
    expect(mainSource).toContain("L'application affiche automatiquement l'evenement");
    expect(mainSource).toContain("BRAIN_GMAIL_COM_COMMAND");
    expect(appSource).toContain('latestAssistant?.text.includes("GMAIL_RESULT")');
    expect(rendererSource).not.toContain("stripGmailCodeActLines");
    expect(rendererSource).not.toContain("J'ouvre Gmail dans Web Explorer.");
  });

  it("registers Airbnb as a Brain-backed module CodeAct", () => {
    expect(brainSource).toContain('pub const BRAIN_AIRBNB_COMMAND: &str = "/airbnb_"');
    expect(brainSource).toContain("BRAIN_CODEACT_ROUTING_RULES");
    expect(brainSource).toContain("geographic place plus travel/vacation/stay lexical field means /maps_ first, then /airbnb_");
    expect(brainSource).toContain("Use Airbnb after /maps_ when a geographic place is detected together with travel/vacation/stay language");
    expect(brainSource).toContain("Do not use for city facts, local weather, geography, maps, or routes without travel/vacation/stay intent");
    expect(brainSource).toContain("brain_airbnb_codeact_template()");
    expect(mainSource).toContain('if (moduleId === "airbnb")');
    expect(mainSource).toContain('Template Airbnb: ${BRAIN_AIRBNB_COMMAND}');
    expect(mainSource).toContain("codeact_routing_rules=${BRAIN_CODEACT_ROUTING_RULES}");
    expect(mainSource).toContain("BRAIN_CODEACT_ROUTING_RULES");
    expect(mainSource).toContain("N'utilise ${BRAIN_GOOGLEWEB_COMMAND} que pour une recherche web generique");
    expect(mainSource).toContain("N'utilise pas ${BRAIN_GOOGLEWEB_COMMAND} pour une action Airbnb.");
    expect(mainSource).toContain("function userTextHasTravelOrStayIntent");
    expect(mainSource).toContain("function inferGeographicTargetFromUserText");
    expect(mainSource).toContain("partir|aller");
    expect(mainSource).toContain("applyGeographicTravelAirbnbFallback");
    expect(mainSource).toContain("host_geographic_travel_fallback");
    expect(mainSource).toContain("hostGeographicTravelFallback");
    expect(mainSource).toContain("mapsCodeActLineFromTarget");
    expect(mainSource).toContain("waitForNativeMapsFirstVisual");
    expect(mainSource).toContain("executeAssistantAirbnbCodeAct");
    expect(mainSource).toContain("navigateNativeWebExplorerToAirbnb");
    expect(mainSource).toContain('parsed.hostname === "www.airbnb.com"');
    expect(appSource).toContain('latestAssistant?.text.includes("AIRBNB_RESULT")');
    expect(rendererSource).toContain('[BRAIN_AIRBNB_COMMAND, "Use Airbnb"]');
  });

  it("registers Maps as a Brain-backed Google Earth CodeAct", () => {
    expect(brainSource).toContain('pub const BRAIN_MAPS_COMMAND: &str = "/maps_"');
    expect(brainSource).toContain("brain_maps_codeact_template()");
    expect(brainSource).toContain("Google Earth");
    expect(brainSource).toContain("explicit map, localization, route, coordinates");
    expect(brainSource).toContain("historical, literary, vocabulary, table, classification or explanation request");
    expect(brainSource).toContain("use /websearch_ and then /scrapers_");
    expect(brainSource).toContain("bare /maps_ opens a neutral Earth view");
    expect(brainSource).toContain("never the saved home city");
    expect(brainSource).not.toContain("geographic place detected alone means /maps_");
    expect(brainSource).not.toContain("Default uses the Brain home city");
    expect(mainSource).toContain("${BRAIN_MAPS_COMMAND} exige une intention carte/localisation/itineraire");
    expect(mainSource).toContain("ne suffit jamais: utilise plutot ${BRAIN_WEBSEARCH_COMMAND}");
    expect(mainSource).toContain("n'utilise jamais user_home_location comme cible par defaut");
    expect(mainSource).toContain("Never treat user_home_location as live device geolocation or as the default /maps_ target");
    expect(mainSource).toContain("function inferMapsTargetFromUserText");
    expect(mainSource).toContain("function userTextHasDirectMapsIntent");
    expect(mainSource).toContain("function shouldSuppressMapsForUserText");
    expect(mainSource).toContain("function textLooksLikeMapBackedAnswerIntent");
    expect(mainSource).toContain("commands.includes(BRAIN_MAPS_COMMAND) && textLooksLikeMapBackedAnswerIntent");
    expect(mainSource).toContain("suppressedMapsCodeAct");
    expect(mainSource).toContain("applyGeographicMapsFallback");
    expect(mainSource).toContain('return `${BRAIN_MAPS_COMMAND} target="${target}"`;');
    expect(mainSource).not.toContain("(?:parle|parles|raconte|dis)[-\\s]+moi");
    expect(mainSource).not.toContain("simplePlaceIntro");
    expect(mainSource).toContain("stripCompetingGeographicCodeActLines");
    expect(mainSource).toContain("stripMapsCodeActLines");
    expect(mainSource).toContain("host_geographic_fallback");
    expect(brainSource).toContain("Device location must never be read silently");
    expect(contractSource).toContain("BRAIN_MAPS_COMMAND");
    expect(mainSource).toContain("extractMapsCodeAct");
    expect(mainSource).toContain("navigateNativeWebExplorerToMaps");
    expect(mainSource).toContain("nativeMapsView: WebContentsView | null");
    expect(mainSource).toContain("new WebContentsView");
    expect(mainSource).toContain("webviewTag: true");
    expect(mainSource).toContain("attachNativeMapsView");
    expect(mainSource).toContain("owner.contentView.addChildView(view);");
    expect(mainSource).toContain("owner.contentView.removeChildView(view)");
    expect(mainSource).toContain('partition: "persist:ingen-maps"');
    expect(mainSource).toContain('webContents.send("forge:maps-codeact", request)');
    expect(mainSource).toContain('ipcMain.handle("forge:maps-show"');
    expect(mainSource).toContain('parsed.hostname === "earth.google.com"');
    expect(preloadCjsSource).toContain("showNativeMaps(bounds)");
    expect(preloadCjsSource).toContain('ipcRenderer.invoke("forge:maps-show", bounds)');
    expect(appSource).toContain('latestAssistant?.text.includes("MAPS_RESULT")');
    expect(appSource).toContain("canvasMapsOpen");
    expect(appSource).toContain("onNativeMapsCodeAct");
    expect(appSource).toContain("setMapsWebviewUrl(event.url");
    expect(appSource).toContain("mapsUrl={mapsWebviewUrl}");
    expect(appSource).toContain("mapsOwnerSessionIdRef");
    expect(appSource).toContain('mapsOwnerSessionIdRef.current = panelsChatSnapshot.activeSessionId || "draft"');
    expect(appSource).toContain("hideNativeMaps");
    expect(canvasSource).toContain("GoogleEarthDomWebview");
    expect(canvasSource).toContain("<webview");
    expect(canvasSource).toContain("googleEarthDomUrl");
    expect(rendererSource).toContain("export function blobPathForAttachment");
    expect(canvasSource).toContain("NativeBrowserPager");
    expect(canvasSource).toContain("GoogleEarthIcon");
    expect(canvasSource).toContain("webExplorerModuleId");
    expect(canvasSource).toContain("canvasSurfaces--nativePager");
    expect(stylesSource).toContain(".nativeBrowserPager");
    expect(stylesSource).toContain(".canvasSurfaces--nativePager .webExplorerNativeSlot");
    expect(stylesSource).toContain(".shell--maps-canvas-open .panelsChatBottom");
    expect(stylesSource).toContain(".shell--maps-canvas-open .chatCanvas");
    expect(stylesSource).toContain(".googleEarthDomFrame");
    expect(stylesSource).toContain(".googleEarthDomWebview");
    expect(stylesSource).toContain(".mapsCanvasGrid--earthActive .mapsCanvasPane");
    expect(stylesSource).toContain("bottom: calc(-1 * var(--chat-canvas-bottom))");
    expect(stylesSource).toContain("z-index: 2");
    expect(stylesSource).toContain(".webExplorerNativeSlot--maps.webExplorerNativeSlot--accepted");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).not.toContain(".mapsEarthBlobFade");
    expect(mainSource).toContain("NATIVE_MAPS_EARTH_OVERSCAN_PX.leftRatio");
    expect(mainSource).toContain("requestedLeftOverscan");
    expect(mainSource).toContain("owner.contentView.addChildView(view);");
    expect(mainSource).not.toContain("owner.contentView.addChildView(view, 0)");
    expect(canvasSource).not.toContain("showNativeMaps");
    expect(rendererSource).toContain('[BRAIN_MAPS_COMMAND, "Use Google Earth"]');
  });

  it("renders Gmail and Airbnb CodeAct events with their module logos", () => {
    expect(rendererSource).toContain('command === BRAIN_GMAIL_COMMAND || command === BRAIN_GMAIL_COM_COMMAND');
    expect(rendererSource).toContain('<ModuleLogo id="gmail" />');
    expect(rendererSource).toContain('if (command === BRAIN_AIRBNB_COMMAND) return <ModuleLogo id="airbnb" />');
    expect(stylesSource).toContain(".transcriptCodeActEvent__icon .sidebarModule__logo");
  });

  it("registers Compute as a module that injects formulas into the composer", () => {
    expect(sidebarSource).toContain('{ id: "compute", label: "Compute" }');
    expect(moduleLogosSource).toContain("export function ComputeIcon");
    expect(moduleLogosSource).toContain('if (id === "compute") return <ComputeIcon />');
    expect(appSource).toContain("const [composerModuleId, setComposerModuleId] = useState<SidebarModuleId | null>(null)");
    expect(appSource).toContain("onComposerModuleChange={setComposerModuleId}");
    expect(mainSource).toContain('if (moduleId === "compute")');
    expect(mainSource).toContain("Module actif: Compute");
    expect(mainSource).toContain("BRAIN_NEWCOMPUTE_COMMAND");
    expect(mainSource).toContain("traite-la comme entree Compute");
    expect(rendererSource).toContain("onComposerModuleChange?: (id: SidebarModuleId | null) => void");
    expect(rendererSource).toContain('onComposerModuleChange?.("compute")');
    expect(rendererSource).toContain('void dispatch({ kind: "chat_text_edited", value: nextDraft })');
    expect(rendererSource).toContain("onUseMathInCompute={useMathInCompute}");
    expect(rendererSource).toContain('<ModuleLogo id={composerModule} />');
  });

  it("renders Brain segment events as animated blue-green text instead of a framed blue box", () => {
    expect(stylesSource).toContain("transcriptBrainTextFlow");
    expect(stylesSource).toContain("background-clip: text");
    expect(stylesSource).toContain(".transcriptCodeActEvent--brainSegment-changed .transcriptCodeActEvent__text");
    expect(stylesSource).toContain(".transcriptCodeActEvent__icon .brainSegmentIcon {");
    expect(stylesSource).toContain("animation: transcriptBrainSegmentPulse 1.4s ease-in-out infinite");
    expect(stylesSource).toContain(".transcriptCodeActEvent__icon .brainSegmentIcon path");
    expect(stylesSource).toContain("animation: transcriptBrainSegmentTrace 1.4s ease-in-out infinite");
    expect(stylesSource).toContain("box-shadow: none");
    expect(stylesSource).not.toContain("background: rgba(8, 145, 178, 0.18)");
  });

  it("places the Brain page close control beside the Brain icon without an icon halo", () => {
    expect(appSource).toContain("isFullPageCanvas && !isBrainCanvas");
    expect(appSource).toContain("onCloseProfileCanvas={() => void closeProfileCanvas()}");
    expect(sidebarSource).toContain("onCloseProfileCanvas?: () => void");
    expect(sidebarSource).toContain("<BrainCanvas onClose={onCloseProfileCanvas} />");
    expect(brainCanvasSource).toContain('className="brainCanvas__close"');
    expect(brainCanvasSource).toContain('<span className="brainCanvas__mark"><Glyph kind="brain" size={26} /></span>');
    expect(stylesSource).toContain(".brainCanvas__close");
    expect(stylesSource).toContain(".brainCanvas__close span");
    expect(stylesSource).toContain("border: 0");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain("width: 15px");
    expect(stylesSource).toContain("color: #fff");
    expect(stylesSource).toContain("left: var(--left-panel-offset)");
    expect(stylesSource).toContain("position: fixed");
    expect(stylesSource).toContain("overflow-y: auto");
    expect(stylesSource).toContain("overscroll-behavior-y: contain");
    expect(stylesSource).toContain(".brainCanvas__segments");
    expect(stylesSource).toContain("@container (max-width: 1040px)");
    expect(stylesSource).toContain("grid-template-columns: repeat(2, minmax(0, 1fr))");
    expect(stylesSource).toContain("@container (max-width: 720px)");
    expect(stylesSource).toContain("max-width: 100%");
    expect(stylesSource).toContain(".brainSegment {");
    expect(stylesSource).toContain("white-space: nowrap");
    expect(stylesSource).toContain(".brainCanvas__mark svg");
    expect(stylesSource).not.toContain("drop-shadow(0 0 7px color-mix(in oklab, currentColor");
  });

  it("keeps CodeAct result metadata from creating duplicate Canvas events", () => {
    expect(rendererSource).toContain("if (isCodeActMetadataLine(line))");
    expect(rendererSource).toContain("codeActMetadataDisplayText(line)");
    expect(rendererSource).toContain("if (skippingCodeActMetadata)");
    expect(rendererSource).toContain("const event = codeActEventFromLine(line)");
    expect(rendererSource).not.toContain("const TRANSCRIPT_CODEACT_COMMANDS = [...BRAIN_CODEACT_COMMANDS, BRAIN_AIRBNB_COMMAND]");
  });

  it("mounts the native WebExplorer view instead of leaving the Google placeholder", () => {
    expect(mainSource).toContain("installMainProcessConsoleGuard");
    expect(mainSource).toContain("isBrokenPipeError");
    expect(mainSource).toContain("new BrowserView");
    expect(mainSource).not.toContain("function openGmailBrowserViewProbeWindow");
    expect(mainSource).toContain("function loadNativeWebExplorerTarget");
    expect(mainSource).toContain("nativeWebExplorerLoadedUrl");
    expect(mainSource).toContain("nativeWebExplorerBoundsKey");
    expect(mainSource).toContain("NATIVE_WEBEXPLORER_VIEWPORT_FADE_CSS");
    expect(mainSource).toContain("installNativeWebExplorerViewportFade(view)");
    expect(mainSource).toContain("view.webContents.insertCSS");
    expect(mainSource).toContain("configureNativeWebExplorerSession");
    expect(mainSource).toContain("setPermissionRequestHandler");
    expect(mainSource).toContain("webRequest.onBeforeRequest");
    expect(mainSource).toContain('parsed.hostname === "accounts.google.com"');
    expect(mainSource).toContain("gmailWebExplorerNavigationUrl(request)");
    expect(mainSource).toContain("nativeWebExplorerTargetUrl = navigationUrl");
    expect(mainSource).toContain("function isGmailMarketingLandingUrl");
    expect(mainSource).toContain("callback({ redirectURL: GMAIL_SIGN_IN_URL })");
    expect(mainSource).toContain('loadNativeWebExplorerTarget(view, "gmail-landing-redirect")');
    expect(mainSource).toContain("attachNativeWebExplorerView(owner, view)");
    expect(mainSource).toContain("owner.addBrowserView(view)");
    expect(mainSource).toContain("owner.setTopBrowserView(view)");
    expect(mainSource).not.toContain("nativeWebExplorerOwner?.setTopBrowserView(nativeWebExplorerView)");
    expect(mainSource).toContain("owner?.removeBrowserView(view)");
    expect(mainSource).toContain("view.setBackgroundColor(\"#ffffff\")");
    expect(mainSource).toContain("view.webContents.setUserAgent(CHATGPT_USER_AGENT)");
    expect(mainSource).toContain('loadNativeWebExplorerTarget(view, "show")');
    expect(mainSource).toContain('preload: join(shellRoot, "preload.cjs")');
    expect(preloadCjsSource).toContain("showNativeWebExplorer(bounds)");
    expect(preloadCjsSource).toContain('ipcRenderer.invoke("forge:webexplorer-show", bounds)');
    expect(preloadCjsSource).toContain("updateNativeWebExplorerBounds(bounds)");
    expect(preloadCjsSource).toContain('ipcRenderer.invoke("forge:webexplorer-bounds", bounds)');
    expect(preloadCjsSource).toContain("hideNativeWebExplorer()");
    expect(preloadCjsSource).toContain('ipcRenderer.invoke("forge:webexplorer-hide")');
    expect(preloadCjsSource).toContain("onNativeWebExplorerCodeAct(listener)");
    expect(canvasSource).toContain("syncNativeWebExplorerBounds");
    expect(canvasSource).toContain("nativeWebExplorerAccepted");
    expect(canvasSource).toContain("nativeWebExplorerStatus");
    expect(canvasSource).toContain("nativeWebExplorerLastBoundsRef");
    expect(canvasSource).toContain("nativeWebExplorerMotionSyncRef");
    expect(canvasSource).toContain("useLayoutEffect");
    expect(canvasSource).toContain("runMotionSync(420)");
    expect(canvasSource).toContain("leftPanelOpen");
    expect(stylesSource).toContain(".canvasSurfaces--webExplorerOpen");
    expect(stylesSource).toContain("top: 96px");
    expect(stylesSource).toContain("bottom: var(--chat-canvas-bottom)");
    expect(stylesSource).toContain("transition: none");
    expect(stylesSource).toContain("inset: 0 24px");
    expect(canvasSource).toContain("webExplorerNativeSlot--accepted");
    expect(canvasSource).toContain("settleTimers.push");
    expect(canvasSource).toContain("[webexplorer] native view rejected");
  });

  it("restores a persisted chat transcript when a sidebar session is opened", () => {
    expect(mainSource).toContain("function restoreChatSessionToCanvas");
    expect(mainSource).toContain("let chatArchiveLoadPromise");
    expect(mainSource).toContain("await loadChatArchive()");
    expect(mainSource).toContain("materializeOpenedChatSession(command.sessionId, command.section)");
    expect(mainSource).toContain("restoreChatSessionToCanvas(command.sessionId)");
    expect(mainSource).toContain("clearPanelsChatSessionForId(command.sessionId)");
    expect(mainSource).toContain("syncLocalChatSessionsFromArchive()");
    expect(mainSource).toContain("for (const attachment of message.attachments ?? [])");
    expect(mainSource).toContain("(message.attachments ?? []).map(publicArchiveAttachmentPreview)");
    expect(mainSource).toContain("resetPanelsChatSessionView()");
    expect(mainSource).toContain("generateChatSessionId()");
    expect(mainSource).toContain('message.role === "user" || message.role === "assistant"');
    expect(sidebarSource).toContain("await panelsChatBottomStore.refresh()");
  });

  it("unmounts the welcome GPU cover once the selected session has messages", () => {
    expect(appSource).toContain("const sessionHasStarted = useMemo");
    expect(appSource).toContain("panelsChatSnapshot.transcript.some");
    expect(appSource).toContain('message.role === "user" || message.role === "assistant"');
    expect(appSource).toContain("!isFullPageCanvas && !sessionHasStarted");
    expect(appSource).toContain("<ProfileCoverBanner");
  });

  it("lets the user send an attachment-only message and keeps sent previews visible", () => {
    expect(rendererSource).toContain("submitText.trim() || uploadPreviews.length > 0");
    expect(rendererSource).toContain("message.attachments ?? []");
    expect(rendererSource).toContain("function TranscriptAttachmentStack");
    expect(rendererSource).toContain("function isTranscriptVisualAttachment");
    expect(rendererSource).toContain("function TranscriptVisualAttachmentEvents");
    expect(rendererSource).toContain("visualAttachmentEventLabel");
    expect(rendererSource).toContain("const visualAttachments = attachments.filter(isTranscriptVisualAttachment)");
    expect(rendererSource).toContain("<TranscriptVisualAttachmentEvents previews={visualAttachments} />");
    expect(rendererSource).toContain("<TranscriptAttachmentStack previews={visualAttachments} onEditImage={onEditImage} />");
    expect(rendererSource).toContain("stage_attachment_for_edit");
    expect(rendererSource).toContain("composerImageEditPill");
    expect(storeSource).toContain("const attachments = state.snapshot.composer.uploadPreviews");
    expect(storeSource).toContain("attachmentIds: attachments.map((attachment) => attachment.id)");
    expect(storeSource).toContain("if (command.kind === \"send_chat\" && !result.accepted)");
    expect(storeSource).toContain("uploadPreviews: []");
  });

  it("shows an assistant writing placeholder while the LLM response is still in flight", () => {
    expect(storeSource).toContain("const pendingAssistantMessage: TranscriptMessage");
    expect(storeSource).toContain("assistant-pending-");
    expect(storeSource).toContain("function mergeInFlightPendingSnapshot");
    expect(storeSource).toContain("let inFlightChatRequests = 0");
    expect(storeSource).toContain("mergeInFlightPendingSnapshot(await api.getPanelsChatBottomSnapshot(), state.snapshot, inFlightChatRequests)");
    expect(storeSource).toContain("const nextTranscript =");
    expect(storeSource).toContain(": [...state.snapshot.transcript, optimisticMessage, pendingAssistantMessage]");
    expect(rendererSource).toContain("function PendingAssistantText");
    expect(rendererSource).toContain("if (!assistantPending && !message.text.trim() && attachments.length === 0)");
    expect(rendererSource).toContain("agentName");
    expect(rendererSource).toContain("is thinking");
    expect(rendererSource).toContain("assistantThinkingEvent");
    expect(rendererSource).toContain("sessionRow__loaderViewbox assistantThinkingEvent__loaderViewbox");
    expect(rendererSource).toContain("assistantThinkingEvent__loaderViewbox");
    expect(rendererSource).toContain('<span className="loader" />');
    expect(rendererSource).toContain("assistantPending");
    expect(rendererSource).toContain("transcriptPill--assistantPending");
    expect(stylesSource).toContain(".assistantText--pending .loader");
    expect(stylesSource).toContain(".assistantThinkingEvent");
    expect(stylesSource).toContain(".assistantThinkingEvent__loaderViewbox");
    expect(stylesSource).toContain(".assistantThinkingEvent__label strong");
  });

  it("keeps uploaded visual media uncut while assistant thinking is pending", () => {
    expect(rendererSource).toContain('preserveAspectRatio="xMidYMid meet"');
    expect(stylesSource).toContain(".transcriptAttachment--video .transcriptAttachment__media");
    expect(stylesSource).toContain("object-fit: contain");
    expect(stylesSource).not.toContain("Fill the blob so no straight letterbox edge cuts through the feathered mask.");
  });

  it("keeps the composer send button as the base arrow while a send is pending", () => {
    expect(rendererSource).toContain("composerSendBusy");
    expect(rendererSource).toContain("beginComposerSendBusy");
    expect(rendererSource).toContain("dispatchTrackedComposerSend");
    expect(rendererSource).toContain('aria-label={composerSendBusy ? "Sending message" : "Send message"}');
    expect(rendererSource).toContain('aria-busy={composerSendBusy}');
    expect(rendererSource).toContain('<svg className="sendGlyph" width="18" height="18" viewBox="0 0 24 24" aria-hidden="true">');
    expect(rendererSource).not.toContain('<span className="loader" aria-hidden="true" />');
    expect(rendererSource).not.toContain("sendPixelLoader");
    expect(rendererSource).not.toContain("sendPixelLoader__pixel");
    expect(rendererSource).not.toContain("composer__send--loading");
    expect(stylesSource).not.toContain(".composer__send--loading");
    expect(stylesSource).not.toContain("/* From Uiverse.io by Fernando-sv */");
    expect(stylesSource).not.toContain("animation: spin89345 1s linear infinite;");
    expect(stylesSource).not.toContain("@keyframes spin89345");
    expect(stylesSource).not.toContain("sendPixelLoader");
    expect(stylesSource).not.toContain("sendPixelTrace");
    expect(composerBurstSource).toContain("onComplete?: () => void");
    expect(composerBurstSource).toContain("onComplete?.()");
    expect(rendererSource).toContain("burst.fire(composerRef.current, () => commit(false), endComposerSendBusy)");
  });

  it("renders loop-stream assistant work like compact Codex command separators", () => {
    expect(rendererSource).toContain("event_group");
    expect(rendererSource).toContain("function groupAssistantCodeActEvents");
    expect(rendererSource).toContain("function TranscriptCommandSummaryLine");
    expect(rendererSource).toContain("commands executed");
    expect(rendererSource).toContain("Executed command tree");
    expect(rendererSource).toContain("function activeAgentEventText");
    expect(rendererSource).toContain("is using");
    expect(rendererSource).toContain("transcriptCodeActEvent--agent-pending");
    expect(rendererSource).toContain("transcriptCodeActEvent--agent-complete");
    expect(rendererSource).toContain("isAgentFileModificationCommand(event.command)");
    expect(rendererSource).toContain("function agentFileModificationSummary");
    expect(rendererSource).toContain("function AnimatedModificationCounter");
    expect(rendererSource).toContain("Modified");
    expect(rendererSource).toContain("CONTEXT_COMPACTION_COMMAND");
    expect(rendererSource).toContain("function TranscriptContextCompactionEventLine");
    expect(rendererSource).toContain("Compressing context");
    expect(rendererSource).toContain("Context compressed");
    expect(rendererSource).toContain("transcriptCodeActFileEvent__fileCard");
    expect(rendererSource).toContain("transcriptCodeActFileEvent__counter");
    expect(rendererSource).toContain("transcriptItem--assistantLoop");
    expect(stylesSource).toContain(".transcriptCommandSummaryLine");
    expect(stylesSource).toContain(".transcriptCommandSummaryLine__icon");
    expect(stylesSource).toContain(".transcriptCommandTree");
    expect(stylesSource).toContain(".transcriptCommandTree__branch");
    expect(stylesSource).toContain("transcriptAgentEventPulse");
    expect(stylesSource).toContain("transcriptAgentEventSettle");
    expect(stylesSource).toContain(".transcriptCodeActEvent--fileModification");
    expect(stylesSource).toContain(".transcriptCodeActFileEvent__added");
    expect(stylesSource).toContain(".transcriptCodeActFileEvent__removed");
    expect(stylesSource).toContain(".transcriptContextCompactionEvent");
    expect(stylesSource).toContain("transcriptContextCompactionLine");
    expect(stylesSource).toContain("transcriptContextCompactionInk");
    expect(stylesSource).toContain(".transcriptItem--assistantLoop");
  });

  it("keeps the canvas scrolled to the newest message while the assistant is writing", () => {
    expect(rendererSource).toContain("function followTranscriptLatest");
    expect(rendererSource).toContain("function latestTranscriptContainerFor");
    expect(rendererSource).toContain("followTranscriptLatest(messagesRef.current, \"smooth\")");
    expect(rendererSource).toContain("followTranscriptLatest(latestTranscriptContainerFor(textRef.current))");
    expect(rendererSource).toContain("[visibleCharacters]");
    expect(rendererSource).toContain("const cadence = totalCharacters - current > 900 ? 62 : 78");
    expect(rendererSource).toContain("const stepBudget = Math.max(1, Math.min(2, Math.floor(elapsed / cadence)))");
    expect(rendererSource).toContain("let hadPendingBeforeRender");
    expect(rendererSource).toContain("const pendingResolvedThisRender = hadPendingBeforeRender && !hasPendingAssistant");
    expect(rendererSource).toContain("message.id === latestAssistantMessageId || pendingResolvedThisRender");
    expect(rendererSource).toContain("queue: string[]");
    expect(rendererSource).toContain("animationState.queue.push(message.id)");
    expect(rendererSource).toContain("assistantShouldAnimate = animationState.queue[0] === message.id");
    expect(rendererSource).toContain("const assistantAwaitingAnimation = assistantPending || assistantQueued");
    expect(stylesSource).toContain("--transcript-bottom-breathing-room: 48px");
    expect(stylesSource).toContain("padding-bottom: var(--transcript-bottom-breathing-room)");
  });

  it("renders assistant markdown as readable headings, lists, and inline emphasis", () => {
    expect(rendererSource).toContain("function assistantMarkdownBlocks");
    expect(rendererSource).toContain("function assistantMathLabel");
    expect(rendererSource).toContain("TEXTUAL_MATH_ATOM_SOURCE");
    expect(rendererSource).toContain("TEXTUAL_MATH_PATTERN");
    expect(rendererSource).toContain("TEXTUAL_MATH_SEQUENCE_SOURCE");
    expect(rendererSource).toContain("function assistantMathTokenNode");
    expect(rendererSource).toContain("function assistantPlainTextNodes");
    expect(rendererSource).toContain("function assistantInlineNodes");
    expect(rendererSource).toContain("assistantText__mathToken");
    expect(rendererSource).toContain("assistantText__mathPill");
    expect(rendererSource).toContain("assistantText__mathComputeHint");
    expect(rendererSource).toContain("Use this math in Compute");
    expect(rendererSource).toContain('type="button"');
    expect(rendererSource).toContain("onClick={() => onUseMathInCompute?.(formula)}");
    expect(rendererSource).toContain("<NewComputeCodeActIcon />");
    expect(rendererSource).toContain("Use in Compute");
    expect(rendererSource).toContain("\\\\\\[[\\s\\S]+?\\\\\\]");
    expect(rendererSource).toContain("{3,}");
    expect(rendererSource).toContain("assistantMathTokenNode(formula");
    expect(rendererSource).toContain("assistantPlainTextNodes(text.slice(cursor, match.index)");
    expect(rendererSource).toContain(".replace(/\\\\quad/g");
    expect(rendererSource).toContain(".replace(/\\\\dots/g");
    expect(rendererSource).toContain("function AssistantMarkdownText");
    expect(rendererSource).toContain("type AssistantTableAlignment");
    expect(rendererSource).toContain("type AssistantCalloutTone");
    expect(rendererSource).toContain("function markdownFenceInfo");
    expect(rendererSource).toContain("function taskListItemFromLine");
    expect(rendererSource).toContain("function AssistantTaskCheck");
    expect(rendererSource).toContain("function quoteTextFromLine");
    expect(rendererSource).toContain("function calloutFromLine");
    expect(rendererSource).toContain("function factItemFromLine");
    expect(rendererSource).toContain("function assistantMacroListItemFromText");
    expect(rendererSource).toContain("function assistantMacroListItems");
    expect(rendererSource).toContain("function splitMarkdownTableRow");
    expect(rendererSource).toContain("function markdownTableAlignments");
    expect(rendererSource).toContain('kind: "table"');
    expect(rendererSource).toContain('kind: "task_list"');
    expect(rendererSource).toContain('kind: "code"');
    expect(rendererSource).toContain('kind: "quote"');
    expect(rendererSource).toContain('kind: "callout"');
    expect(rendererSource).toContain('kind: "facts"');
    expect(rendererSource).toContain('kind: "divider"');
    expect(rendererSource).toContain("assistantText__tableWrap");
    expect(rendererSource).toContain("assistantText__taskList");
    expect(rendererSource).toContain("assistantText__codeBlock");
    expect(rendererSource).toContain("assistantText__codeHeader");
    expect(rendererSource).not.toContain("assistantText__codeWindowDots");
    expect(rendererSource).toContain("assistantText__codeLanguage");
    expect(rendererSource).toContain("assistantText__quote");
    expect(rendererSource).toContain("assistantText__callout--");
    expect(rendererSource).toContain("assistantText__factGrid");
    expect(rendererSource).toContain("assistantText__divider");
    expect(rendererSource).toContain("assistantText__tableCell--");
    expect(rendererSource).toContain("assistantText__heading");
    expect(rendererSource).toContain("assistantText__list");
    expect(rendererSource).toContain("assistantText__list--macro");
    expect(rendererSource).toContain("assistantText__macroLabel");
    expect(rendererSource).toContain("assistantText__macroBody");
    expect(rendererSource).toContain("AssistantMarkdownText messageId={message.id}");
    expect(stylesSource).toContain("--assistant-mark-accent");
    expect(stylesSource).toContain("--assistant-mark-line");
    expect(stylesSource).toContain("--assistant-mark-radius");
    expect(stylesSource).toContain(".assistantText__body");
    expect(stylesSource).toContain(".assistantText__heading");
    expect(stylesSource).toContain(".assistantText__list");
    expect(stylesSource).toContain(".assistantText__list li::before");
    expect(stylesSource).toContain("ol.assistantText__list");
    expect(stylesSource).toContain(".assistantText__list--macro");
    expect(stylesSource).toContain(".assistantText__macroLabel");
    expect(stylesSource).toContain(".assistantText__macroBody");
    expect(stylesSource).not.toContain(".assistantText__list li:nth-child(3n + 2)");
    expect(stylesSource).not.toContain(".assistantText__list li:nth-child(4n)");
    expect(stylesSource).toContain(".assistantText__tableWrap");
    expect(stylesSource).toContain(".assistantText__table");
    expect(stylesSource).toContain(".assistantText__tableCell--right");
    expect(stylesSource).toContain(".assistantText__taskList");
    expect(stylesSource).toContain(".assistantText__taskCheckRail");
    expect(stylesSource).toContain(".assistantText__taskCheckDot");
    expect(stylesSource).toContain(".assistantText__taskCheck--checked .assistantText__taskCheckDot");
    expect(stylesSource).not.toContain(".assistantText__taskItem:nth-child(3n + 2)");
    expect(stylesSource).not.toContain(".assistantText__taskItem:nth-child(4n)");
    expect(stylesSource).toContain("prefers-reduced-motion: reduce");
    expect(stylesSource).toContain(".assistantText__taskItem--checked");
    expect(stylesSource).toContain(".assistantText__taskText");
    expect(stylesSource).toContain(".assistantText__codeBlock");
    expect(stylesSource).toContain(".assistantText__codeHeader");
    expect(stylesSource).not.toContain(".assistantText__codeWindowDots");
    expect(stylesSource).toContain(".assistantText__codeLanguage");
    expect(stylesSource).toContain("box-shadow: none");
    expect(stylesSource).toContain("border-left: 0");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain(".assistantText__quote");
    expect(stylesSource).toContain(".assistantText__quote::before");
    expect(stylesSource).toContain("border-left: 1px solid var(--assistant-mark-line)");
    expect(stylesSource).toContain("overflow: visible");
    expect(stylesSource).not.toContain("border-radius: 22px 13px 24px 11px / 16px 24px 15px 22px");
    expect(stylesSource).toContain('content: "\\201C"');
    expect(stylesSource).toContain(".assistantText__callout--warning");
    expect(stylesSource).toContain("grid-template-columns: minmax(0, 1fr)");
    expect(stylesSource).toContain(".assistantText__callout strong::after");
    expect(stylesSource).toContain("display: none");
    expect(stylesSource).toContain("background: transparent");
    expect(stylesSource).toContain(".assistantText__factGrid");
    expect(stylesSource).toContain("border-block: 1px solid");
    expect(stylesSource).toContain("grid-template-columns: minmax(74px, max-content) minmax(0, 1fr)");
    expect(stylesSource).toContain(".assistantText__fact:nth-child(-n + 2)");
    expect(stylesSource).toContain(".assistantText__divider");
    expect(stylesSource).toContain(".assistantText strong");
    expect(stylesSource).toContain(".assistantText code");
    expect(stylesSource).toContain("background: var(--forge-sidebar-bg)");
    expect(stylesSource).toContain("border-radius: 4px !important");
    expect(stylesSource).toContain("color-mix(in oklab, var(--forge-sidebar-bg), var(--forge-text) 10%)");
    expect(stylesSource).toContain(".assistantText__mathToken");
    expect(stylesSource).toContain(".assistantText__mathPill");
    expect(stylesSource).toContain("box-shadow: none");
    expect(stylesSource).toContain(".assistantText__mathComputeHint");
    expect(stylesSource).toContain("appearance: none");
    expect(stylesSource).toContain("cursor: pointer");
    expect(stylesSource).toContain("max-width: 18px");
    expect(stylesSource).toContain("max-width: 128px");
    expect(stylesSource).toContain(".assistantText__mathComputeHint:focus-visible");
    expect(stylesSource).toContain(".assistantText__mathComputeIcon .boundedFill");
    expect(stylesSource).toContain(".assistantText__mathComputeLabel");
    expect(stylesSource).toContain("overflow-wrap: anywhere");
  });

  it("seeds a fictive assistant pattern gallery session for visual review", () => {
    expect(mainSource).toContain("ASSISTANT_PATTERN_DEMO_SESSION_ID");
    expect(mainSource).toContain("function assistantPatternDemoArchiveSession");
    expect(mainSource).toContain("assistant-writing-patterns-gallery-demo");
    expect(mainSource).toContain("Assistant writing patterns gallery");
    expect(mainSource).toContain("ensureAssistantPatternDemoSession()");
    expect(mainSource).toContain("pattern-demo-assistant-summary");
    expect(mainSource).toContain("pattern-demo-assistant-plan");
    expect(mainSource).toContain("pattern-demo-assistant-pros-cons");
    expect(mainSource).toContain("pattern-demo-assistant-table");
    expect(mainSource).toContain("pattern-demo-assistant-code");
    expect(mainSource).toContain("pattern-demo-assistant-data");
    expect(mainSource).toContain("pattern-demo-assistant-command");
    expect(mainSource).toContain("pattern-demo-assistant-log");
    expect(mainSource).toContain("pattern-demo-assistant-math");
    expect(mainSource).toContain("pattern-demo-assistant-decision");
    expect(mainSource).toContain("pattern-demo-assistant-questions");
    expect(mainSource).toContain("pattern-demo-assistant-checklist");
    expect(mainSource).toContain("pattern-demo-assistant-quote");
    expect(mainSource).toContain("pattern-demo-assistant-callout");
    expect(mainSource).toContain("pattern-demo-assistant-facts");
    expect(mainSource).toContain("pattern-demo-assistant-divider");
  });

  it("projects injected attachments into the current session Files pane", () => {
    expect(appSource).toContain("const sessionFiles = useMemo<ComposerUploadPreview[]>");
    expect(appSource).toContain("for (const file of message.attachments ?? [])");
    expect(appSource).toContain("sessionFiles={sessionFiles}");
    expect(rendererSource).toContain("export function UploadPreview");
    expect(canvasSource).toContain("function CanvasFilesPane");
    expect(rendererSource).toContain("export function TranscriptAttachmentEventIcon");
    expect(canvasSource).toContain("TranscriptAttachmentEventIcon");
    expect(canvasSource).toContain("function AllFilesIcon");
    expect(canvasSource).toContain("function EmptyFilesIcon");
    expect(canvasSource).not.toContain("function EmptyFilesIllustration");
    expect(canvasSource).toContain("fileKindIconKind");
    expect(canvasSource).toContain("canvasFileTile");
    expect(canvasSource).toContain("canvasFileTile__caption");
    expect(canvasSource).toContain("<UploadPreview preview={file} />");
    expect(canvasSource).toContain("stageCanvasImageForEdit(file)");
    expect(canvasSource).toContain("<strong>{file.name}</strong>");
    expect(canvasSource).toContain('filter.id === "all" ? <AllFilesIcon />');
    expect(canvasSource).toContain("className=\"canvasFileTile__captionIcon\"");
    expect(canvasSource).toContain("<TranscriptAttachmentEventIcon kind={file.kind} />");
    expect(canvasSource).not.toContain("<span>{file.kind}</span>");
    expect(canvasSource).toContain("canvasFilesPane__list--empty");
    expect(canvasSource).toContain("No files yet in this session.");
    expect(canvasSource).toContain("No files in this selected session.");
    expect(canvasSource).toContain("<EmptyFilesIcon />");
    expect(canvasSource).not.toContain("<strong>0 files</strong>");
    expect(canvasSource).not.toContain("Attach images, videos, 3D objects or documents.");
    expect(canvasSource).not.toContain("No files in this session.");
    expect(canvasSource).toContain("const fileCountLabel = files.length === 1 ? \"1 file\" : `${files.length} files`");
    expect(canvasSource).toContain("filesLabel={fileCountLabel}");
    expect(canvasSource).toContain("sessionName={sessionName}");
    expect(canvasSource).toContain("type FileKindFilter = \"all\" | \"document\" | ComposerUploadPreview[\"kind\"]");
    expect(canvasSource).toContain("const FILE_KIND_FILTERS");
    expect(canvasSource).toContain("{ id: \"image\", label: \"Images et photos\" }");
    expect(canvasSource).toContain("{ id: \"video\", label: \"Videos\" }");
    expect(canvasSource).toContain("{ id: \"model3d\", label: \"Objets 3D\" }");
    expect(canvasSource).toContain("{ id: \"document\", label: \"Documents\", kinds: [\"pdf\", \"spreadsheet\", \"text\"] }");
    expect(canvasSource).toContain("{ id: \"chart\", label: \"Graphiques\" }");
    expect(canvasSource).toContain("{ id: \"file\", label: \"Autres fichiers\" }");
    expect(canvasSource).toContain("const [kindFilter, setKindFilter] = useState<FileKindFilter>(\"all\")");
    expect(canvasSource).toContain("counts.set(\"document\", (counts.get(\"document\") ?? 0) + 1)");
    expect(canvasSource).toContain("const acceptedKinds = activeFilter?.kinds");
    expect(canvasSource).toContain("if (acceptedKinds && !acceptedKinds.includes(file.kind))");
    expect(canvasSource).toContain("aria-label=\"Classer les fichiers par type\"");
    expect(canvasSource).toContain("setKindFilter(filter.id)");
    expect(canvasSource).not.toContain("canvasFilesPane__header");
    expect(stylesSource).toContain("grid-template-rows: auto auto auto minmax(0, 1fr)");
    expect(stylesSource).not.toContain(".canvasFilesPane__header");
    expect(stylesSource).toContain(".canvasFilesPane__filters");
    expect(stylesSource).toContain(".canvasFileTypeButton");
    expect(stylesSource).toContain("grid-template-columns: var(--workspace-action-icon-size) auto");
    expect(stylesSource).toContain("width: var(--workspace-action-icon-size)");
    expect(stylesSource).toContain("stroke-width: 2.15");
    expect(stylesSource).toContain(".canvasFileTile__captionIcon");
    expect(stylesSource).toContain(".canvasFilesPane__list--empty");
    expect(stylesSource).toContain(".canvasFilesPane__empty svg");
    expect(stylesSource).not.toContain(".emptyFilesIllustration__base");
    expect(stylesSource).toContain(".canvasFilesPane__empty strong");
    expect(stylesSource).toContain("font-size: 18px");
    expect(stylesSource).toContain("gap: 2px");
    expect(stylesSource).toContain("width: 104px");
    expect(stylesSource).toContain("color: currentColor");
    expect(stylesSource).toContain("stroke-width: 0.62");
    expect(stylesSource).toContain("padding: 3px 5px");
    expect(stylesSource).toContain("backdrop-filter: blur(8px)");
    expect(stylesSource).toContain("column-gap: 0");
    expect(stylesSource).toContain("padding: 0 0 16px");
    expect(stylesSource).toContain("margin: 0");
    expect(stylesSource).toContain("box-shadow: none");
  });

  it("keeps visual media in transcript flow while allowing following text to wrap beside it", () => {
    expect(rendererSource).toContain('className = "chatCanvas"');
    expect(rendererSource).not.toContain("stagedVisualAttachments");
    expect(rendererSource).not.toContain("transcriptMediaStage");
    expect(rendererSource).not.toContain("transcriptItem--withVisuals");
    expect(rendererSource).not.toContain("transcriptUserRow--visuals");
    expect(rendererSource).not.toContain("chatCanvas__messages--withVisuals");
    expect(rendererSource).toContain("transcriptFloatMedia");
    expect(stylesSource).toContain("float: right");
    expect(rendererSource).toContain("<TranscriptAttachmentStack previews={visualAttachments} onEditImage={onEditImage} />");
    expect(rendererSource).toContain("imageEditButton--transcript");
    expect(rendererSource).toContain("image added");
    expect(rendererSource).toContain("video added");
    expect(rendererSource).toContain("3D object added");
  });
});
