import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const mainSource = readFileSync(join(process.cwd(), "src", "main", "main.ts"), "utf8");
const generatedSource = readFileSync(join(process.cwd(), "src", "shared", "generated", "forge-ipc.generated.ts"), "utf8");
const brainSource = readFileSync(join(process.cwd(), "..", "..", "src", "brain.rs"), "utf8");
const rendererSource = readFileSync(join(process.cwd(), "src", "renderer", "PanelsChatBottomSlice.tsx"), "utf8");

describe("session rename CodeAct", () => {
  it("injects and executes a Brain-owned short title command", () => {
    expect(brainSource).toContain('pub const BRAIN_RENAME_SESSION_COMMAND: &str = "/rename_session_"');
    expect(brainSource).toContain("brain_rename_session_codeact_template()");
    expect(brainSource).toContain("On the first user message of a session");
    expect(brainSource).toContain('/\\"nomduchat\\"_renamechat_');
    expect(brainSource).toContain("standalone internal line");
    expect(brainSource).toContain("never merge it with visible prose");
    expect(brainSource).toContain("Local action tools exist for user requests");
    expect(brainSource).toContain("Windows/local action tools remain available in Coding Brain for repo inspection");
    expect(generatedSource).toContain('export const BRAIN_RENAME_SESSION_COMMAND = "/rename_session_" as const;');
    expect(generatedSource).toContain("BRAIN_RENAME_SESSION_COMMAND_DESCRIPTION");
    expect(generatedSource).toContain("standalone Brain-owned compact line");
    expect(generatedSource).toContain("never merge it with visible prose");
    expect(generatedSource).toContain("Local action tools exist for user requests");
    expect(generatedSource).toContain("Windows/local action tools remain available in Coding Brain for repo inspection");
    expect(mainSource).toContain("Au premier message utilisateur de cette session");
    expect(mainSource).toContain('/"Titre"_renamechat_');
    expect(mainSource).toContain("une ligne interne seule");
    expect(mainSource).toContain("Ne colle jamais cette ligne a la reponse visible");
    expect(mainSource).toContain('const RENAME_CHAT_CODEACT_SUFFIX = "_renamechat_"');
    expect(mainSource).toContain("COMPACT_RENAME_CHAT_CODEACT_PATTERN");
    expect(mainSource).toContain("_?renamechat_?");
    expect(mainSource).toContain("“”");
    expect(mainSource).toContain("trimmed.match(COMPACT_RENAME_CHAT_CODEACT_PATTERN)");
    expect(mainSource).not.toContain("trimmed.endsWith(RENAME_CHAT_CODEACT_SUFFIX)");
    expect(mainSource).toContain("brain_compact_renamechat");
    expect(mainSource).not.toContain("function firstTurnSessionRenameInput");
    expect(mainSource).not.toContain("function transcriptHasAssistantResponse");
    expect(mainSource).not.toContain("SESSION_TITLE_CODEACT_REQUIRED v1");
    expect(mainSource).not.toContain("...firstTurnSessionRenameInput(userMessageId, transcript)");
    expect(mainSource).toContain('const PENDING_LLM_SESSION_TITLE = "New session"');
    expect(mainSource).toContain("label: PENDING_LLM_SESSION_TITLE");
    expect(mainSource).not.toContain("function sessionLabelFromDraft");
    expect(mainSource).toContain("extractRenameSessionCodeAct");
    expect(mainSource).toContain("function stripRenameSessionCodeActFragments");
    expect(mainSource).toContain('replace(COMPACT_RENAME_CHAT_CODEACT_PATTERN_GLOBAL, "")');
    expect(mainSource).toContain("function stripSessionTitleNoise");
    expect(mainSource).toContain("const normalizedBody = body.replace");
    expect(mainSource).toContain('"$1 $2="');
    expect(mainSource).toContain("function polishedSessionTitle");
    expect(mainSource).not.toContain("applyFirstTurnRuntimeSessionTitle(assistantMessage, session, draft, assistantTitleSource, message.id, requestTranscriptWithUser)");
    expect(mainSource).not.toContain("Decouverte de ${compact}");
    expect(mainSource).not.toContain("Decouverte de ${copiedTalk[1]}");
    expect(mainSource).toContain("Histoire de ${copiedHistory[1]}");
    expect(mainSource).toContain("renameChatSession(session, request)");
    expect(mainSource).toContain("archiveSession.title = request.title");
    expect(mainSource).toContain("function sanitizeAssistantRenameChatter");
    expect(mainSource).toContain("function removeLooseRenameSessionChatter");
    expect(mainSource).toContain("sujet\\s+(?:identifi[eé])?");
    expect(mainSource).toContain("removeRenameSessionChatter(removeLooseRenameSessionChatter(message.text))");
    expect(mainSource).toContain("removeRenameSessionChatter(removeLooseRenameSessionChatter(removeRenameSessionCodeActLines(message.text)))");
    expect(mainSource).toContain("sanitizeAssistantRenameChatter(assistantMessage)");
    expect(mainSource).toContain("const continuationPass = await executeUniversalLoopOrchestratorPass({");
    expect(mainSource).toContain("sujet\\s*:");
    expect(mainSource).not.toContain("renderRenameSessionCodeActResult");
    expect(mainSource).not.toContain("RENAME_SESSION_RESULT");
    expect(mainSource).toContain("executeAssistantRenameSessionCodeAct(assistantMessage, params.session)");
    expect(rendererSource).toContain("BRAIN_RENAME_SESSION_COMMAND");
    expect(rendererSource).toContain("SILENT_TRANSCRIPT_CODEACT_COMMANDS");
    expect(rendererSource).toContain("function isSilentTranscriptCodeActLine");
    expect(rendererSource).toContain("if (isSilentTranscriptCodeActLine(trimmed))");
    expect(rendererSource).toContain("!SILENT_TRANSCRIPT_CODEACT_COMMANDS.has(command)");
  });
});
