export type ForgeShellActionName =
  | "toggle-sidebar"
  | "toggle-right-panel"
  | "close-right-panel"
  | "profile-toggle"
  | "profile-action"
  | "docs-close"
  | "nav-forge"
  | "nav-alpha"
  | "toggle-real-estate"
  | "real-estate-home"
  | "toggle-webexplorer"
  | "open-trading"
  | "toggle-banger"
  | "close-banger"
  | "open-search"
  | "close-search"
  | "toggle-search"
  | "real-estate-new-session"
  | "toggle-real-estate-tools"
  | "close-real-estate-tools"
  | "toggle-real-estate-contacts"
  | "close-real-estate-contacts"
  | "real-estate-automations"
  | "real-estate-properties"
  | "provider-close"
  | "provider-launch-codex"
  | "provider-launch-gemini"
  | "provider-launch-claude"
  | "provider-launch-oanda"
  | "provider-workbench-launch"
  | "provider-workbench-refresh"
  | "provider-refresh-all"
  | "provider-oanda-send"
  | "provider-oanda-reset"
  | "provider-openai-connect"
  | "provider-gemini-save-key"
  | "provider-gemini-connect"
  | "provider-gemini-refresh"
  | "provider-gemini-clear-key"
  | "provider-claude-connect"
  | "provider-claude-refresh"
  | "provider-voice-save-key"
  | "provider-voice-clear-key"
  | "library-toggle"
  | "library-close"
  | "mcp-toggle"
  | "mcp-close"
  | "programs-toggle"
  | "programs-close"
  | "program-create-toggle"
  | "program-create-cancel"
  | "atlas-refresh"
  | "alpha-3d-toggle"
  | "mars-lens-toggle"
  | "mars-lens-close"
  | "alpha-split-toggle"
  | "alpha-3d-new-map"
  | "library-filter"
  | "mcp-filter"
  | "programs-filter"
  | "atlas-subtab"
  | "document-click"
  | "escape-overlays";

export interface ForgeShellActionPayload {
  readonly source?: string;
  readonly kind?: "click" | "shortcut";
  readonly key?: string;
  readonly dataset?: Readonly<Record<string, string>>;
  readonly target?: EventTarget | null;
}

export type ForgeShellActionHandler = (payload: ForgeShellActionPayload) => void;
